### ISSUE TITLE
Remove auto sent mails

### ISSUE THREAD

**Issue by Carrysmatic** [Evolution-WoW/Bug-Report#10]
Current behavior: Remove auto sent mails from server - 
Commendations don' work
Anniversary gifts give timewraped badges in your backpack not currency tab 
Timewalker quests are given for both factions.

How it should work:

Proof (video or image):
![image](https://user-images.githubusercontent.com/100289156/155330857-ef77c7c7-78da-4d67-9bb3-502aee860f69.png)
![image](https://user-images.githubusercontent.com/100289156/155330885-87d7c3ad-569f-4608-a369-421a841be983.png)
![image](https://user-images.githubusercontent.com/100289156/155330979-9a32f28f-b186-45e9-9c10-3cc82c9381b7.png)
![image](https://user-images.githubusercontent.com/100289156/155331314-9e9b94d2-46ba-44d1-ad7d-e9d6ebdf308a.png)

**Comment by Ragelezz** [comment]
Check now on every char combination and let me know. 
@Carrysmatic

**Comment by Ragelezz** [comment]
seems this was fixed, tested on multiple chars, if i missed one mail please open a new bug report
