### ISSUE TITLE
[NPC Scalling] Suramar 113195

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1002]
The NPC " Swarming Vermin" ID 113195 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/970301582849740860/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970301654723358760/unknown.png

**Comment by Ragelezz** [comment]
fixed
