### ISSUE TITLE
The Battle for Broken Shoure- quest scenarios is bugged!

### ISSUE THREAD

**Issue by fuzionproject** [Evolution-WoW/Bug-Report#1007]
Current behavior:  the quest : The Batthe for Broken Shoure - you cant interact with the Npc to take the shep to broken shoure ,,,and quest is look like complete!

How it should work: normaly you click on npc and talk with him to take the shep to broken island..and continue the scenario!

Proof (video or image): https://media.discordapp.net/attachments/825024222497341480/970351983305297962/unknown.png?width=854&height=480  and video link for this quest : https://www.youtube.com/watch?v=NfHxYi9uCqg

**Comment by Foxy19o** [comment]
The quest is set to auto complete.

**Comment by fuzionproject** [comment]
but...where to completre the quest if the npc is missing?
