### ISSUE TITLE
[World Quests] Wrong ilvl Scalling from the rewards of the World Quests Dungeons

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1015]
The scaling ilvl for the world quest rewards is not scaled to 7.0 content.

https://cdn.discordapp.com/attachments/929136522777727056/970375632481583144/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970375700563497000/unknown.png

**Comment by Ragelezz** [comment]
fixed
