### ISSUE TITLE
[NPC Multistack] Dalaran

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1017]
THE NPC "Elite Gryphon" ID 108974 is multistacked in dalaran, krassus landing.

https://cdn.discordapp.com/attachments/929136522777727056/970391708711915551/unknown.png

**Comment by Foxy19o** [comment]
When clicking on the npc it spawns multiple of them. 
![image](https://user-images.githubusercontent.com/59037069/166167521-c7c75164-9e49-4d48-b57d-ca40c28bac8f.png)
Until you click to ride it after it "spawns" 
Gonna leave this issue open for now.

**Comment by Ragelezz** [comment]
fixed
