### ISSUE TITLE
impalement insurance [Stormheim] Storyline Quest

### ISSUE THREAD

**Issue by Herty1** [Evolution-WoW/Bug-Report#1021]
Current behavior: you cant destroy harpune 
![Snímka obrazovky (192)](https://user-images.githubusercontent.com/103910668/166169335-c9ee113a-1824-4e3d-921a-c7f46e5a614a.png)

How it should work: https://www.youtube.com/watch?v=3H5lwEILSnE

https://www.wowhead.com/quest=38615/impalement-insurance

**Comment by Ragelezz** [comment]
if you click on them should grant credit even if you don't destroy them visually
