### ISSUE TITLE
[NPC Scalling] Stormheim 92206

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1023]
The NPC "Felscale Pilferer" ID 92206 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/970707279605268500/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970707311855271946/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970707368339984404/unknown.png

**Comment by Ragelezz** [comment]
fixed
