### ISSUE TITLE
[Stormheim Questline] ID 39850

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1024]
The quest "Sundered" ID 39850 doesn't work because the NPC "Fragment of Will"  is not there.

https://cdn.discordapp.com/attachments/929136522777727056/970725566561017916/unknown.png

This is how it should work:

https://www.youtube.com/watch?v=E4rUA7iN8cI&t=1s
https://www.wowhead.com/quest=39850/sundered#videos:id=100669

**Comment by Ragelezz** [comment]
![WoWScrnShot_050422_142633](https://user-images.githubusercontent.com/69433539/166672623-a215aaa3-4191-4376-9015-7e8a066dd7bb.jpg)
its there
