### ISSUE TITLE
[World Quest] Azsuna ID 44894

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1025]
"Bloodgazer Swarm!" ID 44894

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/970736345045696542/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970736399802302474/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970736438125678642/unknown.png

**Comment by Ragelezz** [comment]
check your ss, you have the quest in log already
