### ISSUE TITLE
[NPC Scalling] Suramar

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1026]
The NPC " Felsoul Trickster" ID 106375 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/970738021920018482/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970739294220201984/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970739648840204338/unknown.png

**Comment by Ragelezz** [comment]
fixed
