### ISSUE TITLE
[Permanent debuff from Elite NPC] NPC ID 101833 

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1034]
After initiating in a combat with the NPC "Revenant Chieftain" NPC 101833 you will receive permanent dot spell from him even after the combat. The spell name is "Defiled Consecration".

https://cdn.discordapp.com/attachments/929136522777727056/971079207515992074/unknown.png - 4:01 server time
https://cdn.discordapp.com/attachments/929136522777727056/971079648744185856/unknown.png - 4:03 server time
https://cdn.discordapp.com/attachments/929136522777727056/971080794183434250/unknown.png - 4:07 server time
https://cdn.discordapp.com/attachments/929136522777727056/971079692708900914/unknown.png - coordinates

**Comment by Ragelezz** [comment]
fixed
