### ISSUE TITLE
[World Quest] Highmountain ID 41013

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1035]
Okay first of all the quest can be completed i just did the progression for the kills works fine (its 10% per 1 elite mob). The problem is that there is a positive bug with the NPC "Stonefist Brawler" ID 102623 where the dmg of the Stone toss is lower than it should (its around 50-60k without the "Bruzelking" buff and around 80-90k with the "Bruzelking" buff" and it should be much higher like 180-190k and 200-220k as in the video below:

https://cdn.discordapp.com/attachments/929136522777727056/971086354735824896/unknown.png - without the buff
https://cdn.discordapp.com/attachments/929136522777727056/971087157949263922/unknown.png - with the buff

This is affected because of the downscalled buff:
https://cdn.discordapp.com/attachments/929136522777727056/971086209369653258/unknown.png

It should be "Damage dealt increased by 100%" and "Damage taken increased by 300%".

Here it should supposed to work:
https://www.youtube.com/watch?v=lUOeMxwhUkA - Time stamp for the Stone toss damage and the buff starts around the 2 min mark of the video.

**Comment by Ragelezz** [comment]
735 client and stats, since we will not change the stats depending on the phases it remains like this, also small note: in the video the build is: Legion Aplha Build 20914 and we use 26972
