### ISSUE TITLE
[World Quest] Stormheim ID 44893

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1036]
"Direbeak Swarm!" ID 44893

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/971168718254116925/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971104722427740210/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971104782464987166/unknown.png

**Comment by Ragelezz** [comment]
quest log
