### ISSUE TITLE
[Quest][Cooking] Too Many Cooks id:40988

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1045]
Current behavior: 

Quest rewards excessive items. 

How it should work:
It shouldn't be a "choose reward" quest. Should give the recipe and 5 dried mackerel strips

https://www.wowhead.com/quest=40988/too-many-cooks

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/166832852-355ee709-4fd4-4910-a934-a469e0b42e50.png)
![image](https://user-images.githubusercontent.com/29517963/166832879-20f526b7-d64e-422e-86ba-63bb50fc585c.png)

**Comment by Ragelezz** [comment]
fixed
