### ISSUE TITLE
[Quest][Engineering][NPC] Endless Possibilities

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1046]
Current behavior:
When returning to the Engineering shop in Broken Isles Dalaran while on the quest, the quest hand-in NPC Didi the Wrench is nowhere to be found.

How it should work:

- https://www.wowhead.com/quest=40854/endless-possibilities
- https://wowpedia.fandom.com/wiki/Endless_Possibilities
- https://www.wowhead.com/npc=93520/didi-the-wrench

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/166835292-2e8ea01c-d3fe-484e-9307-51ebb528a5f0.png)

**Comment by Ragelezz** [comment]
fixed
