### ISSUE TITLE
[World Quest] ID 42027

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1050]
"Faronaar in Chaos" ID 42027

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/971577840170573864/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971577906545446932/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971578050254872616/unknown.png

**Comment by Ragelezz** [comment]
works
![Uploading WoWScrnShot_050722_203832.jpg…]()
