### ISSUE TITLE
[World Quest] Highmountain ID 41622

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1051]
"Crawliac's Legacy" ID 41622

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/971599810035601428/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971600277591453746/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/971600364006686760/unknown.png

**Comment by Ragelezz** [comment]
works
![Uploading WoWScrnShot_050722_203428.jpg…]()
