### ISSUE TITLE
[Zone][NPC] Amal'thuzad id:97132

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1056]
Current behavior:
Amal'Thazad in the death knight order hall is speaking russian instead of english

How it should work:

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/167187576-6bfb2a4b-8ce1-4781-b0fd-42bb76bfa214.png)

**Comment by Ragelezz** [comment]
fixed
