### ISSUE TITLE
[NPC][Phasing] Daumyr id:116130

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1057]
Current behavior:

Daumyr is visible in the death knight class order hall without having completed the required quest.

How it should work:

Should be visible after completing On Daumyrs Wings.

https://www.wowhead.com/npc=116130/daumyr
https://www.wowhead.com/quest=45243/on-daumyrs-wings#comments

Proof (video or image):

![image](https://user-images.githubusercontent.com/29517963/167190202-311dec38-e002-4e34-bd18-c4c32e96e05b.png)

**Comment by Ragelezz** [comment]
intended due to phasing issues.
