### ISSUE TITLE
[Zone][Object] The Wandering Isle

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1058]
Current behavior:

The mission table for the Monk Class Order Hall is missing. Only the collision box is there. This makes Monks unable to progress further.

How it should work:

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/167207209-8f63a595-9203-4e31-ab70-51cba5304977.png)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/990
?? have you progressed through your campaign ?

**Comment by arft1kwerg** [comment]
Yes. Character went through the class hall starting scenario (Assult on the Peak of Serenity) and then follow the quest chain up to "Tianji of the Ox" (id:41945) where you have to interact with the mission table and complete a mission. Since the table isn't spawned the quest remains in an uncompletable state (Have deleted the cache, but it doesn't make it spawn in).

Furthermore, due to the inability to interact with the mission table, it is impossible to get the assult quest which starts each respective zone's questlines.

**Comment by Ragelezz** [comment]
fixed, after rr
