### ISSUE TITLE
[Quest][Shaman] The Codex of Ra id:43338

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1068]
Current behavior:

Entering the halls doesn't complete part of the objective. Multiple events where Xuen is speaking to the player is missing.

How it should work:

When entering the sub-zone, the quest objective to reach the hall should complete. 

https://www.wowhead.com/quest=43338/the-codex-of-ra#comments

https://www.youtube.com/watch?v=rB--zcnj1EI

Proof (video or image):

![image](https://user-images.githubusercontent.com/29517963/167275329-7de53e96-c6af-4622-9211-3df966f70b7b.png)

**Comment by Ragelezz** [comment]
Artifact weapons quest-lines are not working due to the weapon being added when you hit level 100.
