### ISSUE TITLE
Quest Stormheim (paladin class hall table)

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#1074]
It should give you autocomplete when you get to dalaran with the portal so you can continue the quests.
![Annotation 2022-05-08 222724](https://user-images.githubusercontent.com/102504567/167314641-c398367c-8240-43ec-9181-5dd38cb2ebf8.png)
![Annotation 2022-05-08 222739](https://user-images.githubusercontent.com/102504567/167314655-c8aa4360-bb64-41fb-a3a2-efac64b3b4a0.png)
![Annotation 2022-05-08 222750](https://user-images.githubusercontent.com/102504567/167314682-5a1625a0-cad9-427a-b8e7-534d0cecc09b.png)

**Comment by Bajboom** [comment]
![Annotation 2022-05-14 225500](https://user-images.githubusercontent.com/102504567/168447866-844b7a1e-6396-44fc-94b1-9a16f47b5d9a.png)
 Idem Warr !

**Comment by Denimz92** [comment]
Known general issue, needs a general fix.

**Comment by Ragelezz** [comment]
its a visual issue, go to nathanos and speak to him
as you can see in the picture, its till 0/1 but i can complete the quest at npc
![WoWScrnShot_051722_123809](https://user-images.githubusercontent.com/69433539/168780848-6ee4fcc7-d0de-4387-89c2-0c8995b66734.jpg)
