### ISSUE TITLE
[Quest][Valsharah] Entangled Dreams id:38147

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1078]
Current behavior:
Killing Morphael doesn't give credit to the quest. He doesn't play his voicelines as he should.

How it should work:

https://www.youtube.com/watch?v=f4zWFS-2WSY
https://www.wowhead.com/npc=91045/morphael#comments
https://www.wowhead.com/quest=38147/entangled-dreams

Proof (video or image):

![image](https://user-images.githubusercontent.com/29517963/167462617-377f55a5-c16a-421e-8ffe-eb7fb2826eb2.png)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/948
