### ISSUE TITLE
[Quest][Monk] Champion: Taran Zhu id:41734

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1092]
Current behavior:
Picking up the quest only gives a blank quest. Quest cannot be turned in.

How it should work:

Should allow the monk player to recruit Taran Zhu as a order hall follower

https://www.wowhead.com/quest=41734/champion-taran-zhu
https://www.wowhead.com/champion=603/taran-zhu

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/168152723-5fbe1ea8-b72f-47aa-b312-140b0d9683d2.png)

**Comment by NurZooL** [comment]
Still not working.

**Comment by Ragelezz** [comment]
fixed
