### ISSUE TITLE
[Order Hall][Followers] Deactivation cost

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1093]
Current behavior:
Deactivating a follower costs gold.

How it should work:
Followers should only cost gold when they get activated.

Proof (video or image):
![Skärmbild från 2022-05-12 21-29-23](https://user-images.githubusercontent.com/29517963/168153764-3e1e3f36-5ebb-4ffe-810c-e5e300eb173b.png)
![Skärmbild från 2022-05-12 21-29-38](https://user-images.githubusercontent.com/29517963/168153768-870f6654-b7c5-440e-bc5c-2c2e51c8c09d.png)

**Comment by Ragelezz** [comment]
**Reactivating**

**Comment by arft1kwerg** [comment]
Issue has not been fixed
https://user-images.githubusercontent.com/29517963/169572685-59be95b9-d5c2-4898-9c92-ffafbed2a4d8.mp4
