### ISSUE TITLE
[Highmountain][Object] Darkshard Crystal id:100418

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1100]
Current behavior:
Doesn't always spawn a Darkshard Crystal when interacted with. Players can interact with the object without being on the correct quest.

How it should work:

Players should only be able to interact with this object while on the quest 'To See the Past'. When the player interacts with the Crystal, it should summon a Darkshard Crystal

https://www.wowhead.com/npc=100418/darkshard-crystal (object)
https://www.wowhead.com/spell=197686/summon-darkshard-crystal#summons
https://www.wowhead.com/npc=100445/darkshard-crystal (mob)
https://www.wowhead.com/quest=40520/to-see-the-past

Proof (video or image):

https://user-images.githubusercontent.com/29517963/168429988-5b028d3b-d64d-4f4c-8e43-4e62c6df3748.mp4

**Comment by Denimz92** [comment]
![image](https://user-images.githubusercontent.com/16610472/168463667-b9ac990d-d55b-499c-a736-66966cc71aa7.png)

Object works, turn off your UI/loot addons and retry.

**Comment by arft1kwerg** [comment]
https://user-images.githubusercontent.com/29517963/168464613-8d88ba01-c712-41d8-80c9-2f2de6434aa4.mp4
