### ISSUE TITLE
[NPC][Suramar] Thaedris Feathersong id:99065

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1105]
Current behavior:
NPC isn't offering the quests 'The Lost Advisor' and 'An Ancient Recipe' at the same time.

How it should work:
The player should be able to pick up both 'The Lost Advisor' and 'An Ancient Recipe' 

Proof (video or image):

https://www.wowhead.com/quest=40266/the-lost-advisor#comments
https://www.wowhead.com/quest=40744/an-ancient-recipe
https://www.youtube.com/watch?v=8VPtMwlm3g4&t=10s (You can see both quests being offered at ~10 seconds into the video)

**Comment by Ragelezz** [comment]
intended order
