### ISSUE TITLE
[Rogue] Envenom

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#111]
Current behavior: When i hit Envenom instead of consuming combo points it resets to 3cp wich means you can spam it if you have energy! and the poison buff aplication chance by 30%  stays only 3 seconds no matter how many combo points !

How it should work: Envenom consumes combo points and also the buff duration on you should be 1cp - 2sec , 2cp - 3sec , 3cp - 4sec , 4cp - 5sec , 5cp - 6sec !

Proof (video or image): -

**Comment by Ragelezz** [comment]
pune si spell name in titlu pls

**Comment by Ragelezz** [comment]
fixed
