### ISSUE TITLE
[npc][suramar] Servant of Azoran id:102837

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1112]
Current behavior:
NPC is aggressive and attacks players if they come near.

How it should work:
NPC should be unattackable and cover in fear infront of Lyana Darksorrow (99890

Proof (video or image):

In this video you can see how it covers in fear at around the 1 second mark.
https://www.youtube.com/watch?v=g0kprYCDwFk
https://www.wowhead.com/npc=102837/servant-of-azoran

**Comment by Ragelezz** [comment]
fixed
