### ISSUE TITLE
[Demon Hunter starting quest]

### ISSUE THREAD

**Issue by Foxy19o** [Evolution-WoW/Bug-Report#1116]
Since you start 101 lvl why do Demon Hunters spawn at the capital cities Orgrimmar and Stormwind? 
![image](https://user-images.githubusercontent.com/59037069/168471247-af3bd0f4-a27a-46d6-892b-e55e07e8f9c8.png)
They should spawn in Dalaran so they can continue they qust line as you can see starting from this:
![image](https://user-images.githubusercontent.com/59037069/168471266-ee51c82a-ff03-441b-9881-2d2fb8e0e9b9.png)
No quests can be taken ''The Call of War' or 'Audience with the Warchief''
Make Demon Hunters spawn in Dalaran.

**Comment by Ragelezz** [comment]
there's a portal to the left as you first log in and you are ported to orgrimmar and spawned one in stormwind, you will see it
