### ISSUE TITLE
[NPC][Stormheim] Commander Lorna Crowley id:95889

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#1123]
Current behavior:
Interacting with the NPC doesn't bring up the option to set Hearthstone. Cursor changes to a Hearthstone when mousing over her.

How it should work:
Player should get a pop-up and be able to set their Hearthstone at her location if they speak with her

Proof (video or image):
https://www.wowhead.com/npc=95889/commander-lorna-crowley#comments

Click the Hearthstone filter on the map and she shows up on the left side as an alliance only Hearthstone point
https://www.wowhead.com/stormheim

**Comment by Ragelezz** [comment]
fixed
