### ISSUE TITLE
[Rare Elite] [Suramar]  ID 99792

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#1150]
The Rare Elite "Elfbane" ID 99792 just stays there AFK and does nothing.

https://cdn.discordapp.com/attachments/929136522777727056/976176817931157504/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/976176914819592212/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/976176954569003148/unknown.png

**Comment by Ragelezz** [comment]
fixed
