### ISSUE TITLE
[Rogue] Garrote

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#120]
Current behavior:Garrote adds 2 combo points instead of 1 even there is no critical strike involved

How it should work: if there are no critical hits involved when you garrote it should only add 1cp , it only applies 2 cp only if you crit with  it  due to Seal Fate wich is a passive that says "when you critically strike with a melee attack that generates cp , you gain an additional cp pe critical strike"

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
for the passive make a new bug report pls
