### ISSUE TITLE
[Rogue] Talent - Subterfuge

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#124]
Current behavior: it doesn't apply its effect

How it should work: When you garrote from stealth it should apply it with 125% increase damage and should have no cd when applied from stealth ! also you should be able for 3 more seconds to use the stealth abilities after you break stealth and that is not working aswell !

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed

**Comment by Ragelezz** [comment]
fixed
