### ISSUE TITLE
[Rogue] Venomous Wounds Passive Spell

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#136]
Current behavior: it does not work

How it should work: everytime garrote and rupture deals damage it should recharge energy by 10 and it doesn't ! also this work in combination with Venom Rush Talent wich says the Venomous wounds grants 3 additional Energy eachtime it grants energy wich means if we apply the Venom Rush Talent it should add 13 energy per garrote and rupture tick !

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
