### ISSUE TITLE
[Rogue] Deadly Poison

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#137]
Current behavior: it does not add subsequent nature damage as in tooltip and does not crit also doesn't double hits ! i believe it doesn't hit with the offhand !

How it should work: it should crit and add aditional damage wich doesn't , it should also crit based on stats , also sometimes it doubles the damage per dot because it applies with both weapons per hit wich means it double hits !

Proof (video or image): https://www.youtube.com/watch?v=aFB9S4r_2zo  8.15 minutes !

**Comment by Ragelezz** [comment]
fixed
