### ISSUE TITLE
[Rogue] Nightblade

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#138]
Current behavior: it doesn't last as it should no matter how many combo points i use , it lasts 5 seconds or less no matter what and sometimes doesn't even apply on the target , also it doesn't apply the 15% damage as it should !

How it should work: it should last like this : 1cp - 8 seconds , 2cp - 10 seconds , 3cp - 12 seconds , 4cp - 14 seconds , 5cp - 16 seconds 

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
