### ISSUE TITLE
[Item-Trinket] Spiked Counterweight

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#151]
Current behavior: The effect it hits lower than it should and it does not apply the 15% increase damage as in numbers (the effect is shown as working)

How it should work: melee attacks have a chance to deal more physical damage and should increase all damage by 15% for 15 seconds up to the damage it deals in tooltip (extra damage)

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
