### ISSUE TITLE
[Priest] Penance 

### ISSUE THREAD

**Issue by Mematoru** [Evolution-WoW/Bug-Report#158]
Current behavior: 
1. Penance heals/hits only 2/3 times.
2. Penance damages both enemy and the caster.

How it should work:
1. It should hit 3 times.
2. Shouldn't damage the caster.

Proof (video or image):
![](https://i.imgur.com/8ydBYKr.png)

**Comment by Mematoru** [comment]
Reviewing.

**Comment by Ragelezz** [comment]
fixed
