### ISSUE TITLE
[Paladin][Spell] Infusion of Light does not proc from damage (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#165]
**Current behavior:**
At the moment, the Infusion of Light passive does not proc from Holy Shock offensive crits. (only works for critical heal)
**How it should work:**
The passive should proc when Holy Shock cast is either a critical heal or a critical damage. 

**Proof (video or image):**
![Infusion_issue1](https://user-images.githubusercontent.com/100310056/155886676-2e43236b-1030-443f-80ca-506d462d77bb.PNG)

**Comment by Mematoru** [comment]
Fixed.
