### ISSUE TITLE
[Shaman] Earth Elemental not summoned

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#17]
Current behavior:  Earth elemental is not summoned when actioned

How it should work:  Should be spawned

Proof (video or image):

![missing earth elemental](https://user-images.githubusercontent.com/16610472/155363934-44374196-1a81-44c6-ad58-a71fdea41b4c.jpg)

**Comment by Ragelezz** [comment]
fixed
