### ISSUE TITLE
[Warrior] Commanding Shout

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#173]
Current behavior: it doesn't work

How it should work: It should grant you and all party or raid members  withing 30 yards 15% increased maximum health for 10 seconds , after the effect is diminished the health is lost (comes back to normal) !

Proof (video or image):

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/105
u sure ? not sure if i implemented it yet, later today ill implement all fixes
