### ISSUE TITLE
[Warrior] Ayala's Stone Heart Legendary

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#186]
Current behavior: you can literally spam Execute for 9 seconds instead of consume the buff

How it should work: When Stone Heart procs you should be able to Execute with no cost or rage regardless of target health but it should consume the proc and to be able to spam it towards the duration of it wich is 9 seconds

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
