### ISSUE TITLE
[Druid] Clearcasting proc

### ISSUE THREAD

**Issue by Trased** [Evolution-WoW/Bug-Report#19]
Current behavior:  Clearcasting [aura id= 135700] currently procs after each melee attack.
Passive id: Omen of Clarity -  16864

How it should work:  it shouldn't proc after each melee attack, the proc chance has to be lowered.
Quote:
"At the time of this comment, the proc rate for feral Omen of Clarity is 3.5 PPM; in Cat Form this is equivalent to a chance per hit of 5.83333%.

Source: https://twitter.com/Celestalon/status/482329896404799488"
Proof (video or image): https://streamable.com/5o1zlw

**Comment by Ragelezz** [comment]
fixed
