### ISSUE TITLE
[General] Teleporting to Dalaran-Broken Isle

### ISSUE THREAD

**Issue by Chinanrone** [Evolution-WoW/Bug-Report#202]
Current behavior:  Once u get portal to new Dalaran, u get stuck in load screen very long time, works only if u quit game and reenter.

How it should work: -

Proof (video or image): https://imgur.com/4AlTj9V

**Comment by Infinity19o** [comment]
Is this issue still ongoing? 

Haven't had any issues so far loading in Dalaran.

**Comment by Ragelezz** [comment]
closed
