### ISSUE TITLE
[Paladin][Talent] Holy Prism not doing heal/damage (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#22]
**Current behavior:**
At the moment, the spell does not do anything. When using on enemy the target does not receive damage and nearby allies do not receive heal (check the first video) and in for the second case, when using the spell on an ally, the target does not receive heal and nearby enemies do not receive damage (check second video).
**How it should work:**
The spell has a dual effect:
- _when the target is an enemy, the target should receive damage and 5 allies in a 15yd radius of the target should receive heal._
- _when the target is an ally, the target should receive heal and 5 enemies in a 15yd radius of the target should receive damage._

**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155388676-1b164e0f-1e82-49e0-9fcb-532a5efa4ac2.mp4

https://user-images.githubusercontent.com/100310056/155388707-baada16e-bb2d-4e1f-a8d7-05f6d7aabe4b.mp4

**Comment by Ragelezz** [comment]
fixed
