### ISSUE TITLE
Mage blink teleporting under map

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#224]
Current behavior: blink is ignoring terrain. you can blink trough walls

How it should work: when you have a wall you should be able to hit the wall and not go trough it. this will result in you going to the bottom of the map (untextured part of it). be careful so you won't make it to stop on every obstacle. ex you should be able to pass small rocks and wood on the ground, but you can't pass terrain bigger then your character model.

Proof (video or image):
![WoWScrnShot_030222_150719](https://user-images.githubusercontent.com/100777412/156379317-5831db92-281f-42d9-b22a-0d18b4f70c42.jpg)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/8
