### ISSUE TITLE
[Misc] Combo Points generators

### ISSUE THREAD

**Issue by Ragelezz** [Evolution-WoW/Bug-Report#227]
druid and rogue spells which award combo points list below:

**Comment by Mematoru** [comment]
Brutal Slash 	 - 202028   - Druid - 1 combo point
Rake                 - 1822       - Druid - 1 combo point
Shred 		 - 5221       - Druid - 1 combo point
 
Hemorrhage 	    16511    - Rogue - 1 combo point
Toxic Blade 	  - 245388  - Rogue - 1 combo point
Cheap Shot       - 1833      - Rogue - 2 combo points
Fan of Knives     - 51723    - Rogue - 1 combo point
Garrote 	          - 703        - Rogue - 1 combo point
Mutilate 	          - 1329      - Rogue - 2 combo points
Poisoned Knife  - 185565  - Rogue - 1 combo point
Ghostly Strike    - 196937  - Rogue - 1 combo point
Ambush             - 8676     - Rogue - 2 combo points
Gouge               - 1776      - Rogue - 1 combo point
Pistol Shot 	  - 185763  - Rogue - 1 combo point
Saber Slash        - 193315  - Rogue - 1 combo point each time it strikes
Gloomblade	  - 200758  - Rogue - 1 combo point
Backstab            - 53          - Rogue - 1 combo point
Shadowstrike     - 185438  - Rogue - 2 combo points
Shuriken Storm  - 197835  - Rogue - 1 combo point / target hit
Shuriken Toss     - 114014  - Rogue - 1 combo point

**Comment by Ragelezz** [comment]
fixed all
