### ISSUE TITLE
[Paladin][Talent] Devotion Aura not triggered (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#23]
**Current behavior:**
The default aura for the Devotion Aura talent is not triggered when the talent is selected. 
**How it should work:**
When selecting any of the three auras of the level 60 talents line, the paladin should have on them the default effect of that aura. In the case of Devotion Aura, there should be a 20 reduce damage buff split between every ally in a 10yd radius.
**Proof (video or image):**
![DevotionAura_issue1](https://user-images.githubusercontent.com/100310056/155395063-74fe6f7b-c58a-4798-992d-a424c6881aab.PNG)

**Comment by Ragelezz** [comment]
fixed
