### ISSUE TITLE
[Druid][Restoration] Clearcasting 

### ISSUE THREAD

**Issue by Malefique96** [Evolution-WoW/Bug-Report#238]
Current behavior: Clearcasting. 
Passive: Omen of Clarity - You can cast regrowth free for the entire duration. 

How it should work:  It should allow you only 1 regrowth free or 3 (if you play with 'Moment of Clarity (talent)'. 

Proof (video or image): https://www.youtube.com/watch?v=x1Vd2kubW9E    2:15

**Comment by Ragelezz** [comment]
fixed
