### ISSUE TITLE
[Paladin][Spell] Judgement not applying debuff on target 

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#24]
**Current behavior:**
Tested on all specs with the same behavior. **For holy specifically**, when hitting an enemy target with Judgement, the target does not receive the debuff specified in the tooltip. (see first video)
Also, checked to see if the damage is updated even though the debuff is not shown under target nameplate and the buff is not applied. (see second video)
**How it should work:**
Judgement should apply a debuff on the enemy target which increases the damage of the next Crusader Strike /  Holy Shock by 30% for the next 6 seconds.
**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155408424-a3dd90d9-1160-46ce-96e0-a46c6ed4fb78.mp4

https://user-images.githubusercontent.com/100310056/155408454-83218baf-64a6-4048-9c99-15c59347aaec.mp4

![Judgement_issue3](https://user-images.githubusercontent.com/100310056/155408737-31443e7c-efe6-41db-8c02-99897592ab1d.PNG)

**Comment by Ragelezz** [comment]
fixed on all specs
