### ISSUE TITLE
[Druid][Restoration] Efflorescence 

### ISSUE THREAD

**Issue by Malefique96** [Evolution-WoW/Bug-Report#240]
Current behavior: Efflorescence  doesnt work. 

How it should work: Efflorescence grows a healing blossom at the target location, restoring (23.3% of Spell power) health to three injured allies within 10 yards every 2 sec for 30 sec. Limit 1.

Proof (video or image): https://www.youtube.com/watch?v=x1Vd2kubW9E&t=1507s    21:06

**Comment by Ragelezz** [comment]
fixed
