### ISSUE TITLE
[Druid][Restoration] Tranquility 

### ISSUE THREAD

**Issue by Malefique96** [Evolution-WoW/Bug-Report#242]
Current behavior: Tranquility isn't working as it should do. 

How it should work:  When you cast Tranquility you can move while the cast is active.  

Proof (video or image): https://www.youtube.com/watch?v=eVYDBwXaXb0  7:59

**Comment by Ragelezz** [comment]
https://www.wowhead.com/spell=189857/tranquil-mind
invalid, he most probably has this trait.
