### ISSUE TITLE
[Paladin][Talent] Fist of Justice passive not working (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#26]
**Current behavior:**
At the moment the effect of the Fist of Justice talent is not working.

**How it should work:**
Judgement should reduce the remaining cooldown of Hammer of Justice by 10 seconds.

**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155493461-7b578640-1fba-4dd1-adf6-cc4c56587868.mp4

![FistofJustice_issue1](https://user-images.githubusercontent.com/100310056/155493503-d7f770ad-942e-4fb7-9937-4d09cceecf10.PNG)

**Comment by Ragelezz** [comment]
fixed
