### ISSUE TITLE
Mage frost Flurry spell not working properly 

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#263]
Current behavior: So the ablity casts ok, but the big problem here is that you are supposed to have 3 hits on the spell, as the flavor text describes "striking the target 3 times" so it basically dose 1/3 of the total dmg it supposed to do.

How it should work: the spell needs to hit 3 times (like 3 mini frost bolts), each hit refreshing the slow that flurry applies, also when you get a **brain freez prock** this spell is very important for frost mage because it gives us access to the passive **"Shatter"** basically deal a shit ton of dmg in very short period of time. the thing is **if the spell dose not hit 3 times** you won't get access to **"Shatter"** (because of the global cd) so you lose a lot of damage in the rotation.

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![FLURRY JUST 1 HIT](https://user-images.githubusercontent.com/100777412/156593537-3d30b733-8bb6-4cfd-bb8a-900e560121fe.jpg)

**Comment by Hauntspectre** [comment]
Reviewing.

**Comment by Ragelezz** [comment]
fixed
