### ISSUE TITLE
Mage frost Splitting ice 100% dmg

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#268]
Current behavior:  The second ice lance from **Splitting ice** hits for 100% of the dmg.

How it should work: Splitting ice makes ice lance to **hit a second target for _80%_ of the dmg**.

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![Splitting ice 100% dmg](https://user-images.githubusercontent.com/100777412/156602740-b42cc8f5-a121-4069-a236-04cadd436a85.jpg)

**Comment by Hauntspectre** [comment]
Reviewing

**Comment by Hauntspectre** [comment]
Fixed + 5% bonus damage on Ice Lance.
