### ISSUE TITLE
[Paladin][Talent] Greater Judgement passive not working (Retribution)

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#27]
Current behavior:Not applying debuff , not hitting 100% crit if target target is over 50% hp , not hitting another 2 aditional targets

How it should work: Should be 100% crit if target is more than 50% hp , should apply a debuff on target that increases the paladins holy power spenders by a Number% depending on mastery , should bounce in 2 more targets

Proof (video or image):
https://streamable.com/tf9scr

[Imgur](https://imgur.com/ldcniH4)

**Comment by Mematoru** [comment]
100% crit and debuff on targets fixed. 
damage of judgment on all targets later.

**Comment by Mematoru** [comment]
Fixed.
