### ISSUE TITLE
Mage frost- Ring of frost not working at all

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#270]
Current behavior: it's not rooting the target 

How it should work: it should freez all the targets that touch the ring.

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![ring of frost](https://user-images.githubusercontent.com/100777412/156607165-05b564da-61b2-4999-8248-cf6ee0e88d93.jpg)

**Comment by Ragelezz** [comment]
fixed
