### ISSUE TITLE
Mage frost- no bonus dmg on frozen targets

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#271]
Current behavior: the dmg on frozen targets it's unchanged. just as a normal target

How it should work: it should 100% crit on frozen targets and bonus dmg on crit

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![no crit on frozen](https://user-images.githubusercontent.com/100777412/156607767-7336030f-d74c-47eb-bf31-5e1f38e01201.jpg)

**Comment by Hauntspectre** [comment]
Reviewing

**Comment by Ragelezz** [comment]
make a proper bug report next time
1. your target doesn't even have a freeze effect
2. link a spell passive or not which should say that gives bonus damage to frozen targets
