### ISSUE TITLE
Mage frost- Unstable magic talent

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#272]
Current behavior: not working at all. never procs.

How it should work: 20% chance of proccing.

Proof (video or image):

## DON'T FORGET TO LABEL
![unstable magic](https://user-images.githubusercontent.com/100777412/156648343-4456c3d8-1a3c-4aea-9e24-5edc6269a11a.jpg)
 IT ACCORDINGLY TO THE ISSUE.

**Comment by Hauntspectre** [comment]
Reviewing

**Comment by Mematoru** [comment]
Fixed for all specs.
