### ISSUE TITLE
[Shaman][Restoration] Unleash Life

### ISSUE THREAD

**Issue by Chinanrone** [Evolution-WoW/Bug-Report#286]
Direct healing is working but increase effect is not working.

**Comment by Ragelezz** [comment]
healing surge before: 36k
healing surge after: 52k
its working
the actual bug is that is not being consumed after use, can you make a list of all the spells which should consume unleash life?

**Comment by Chinanrone** [comment]
Chain Heal, Healing wave and Healing surge

**Comment by Ragelezz** [comment]
done
