### ISSUE TITLE
Death knight- death coil not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#292]
Current behavior: the spell death coil dose 0 dmg. applying 0 of the effects

How it should work: 

Proof (video or image):

## DON'T FORGET TO LA
![DK- death coil 0 dmg](https://user-images.githubusercontent.com/100777412/156760572-51b7c67e-a988-4ee9-a40f-70cedc331b93.jpg)
BEL IT ACCORDINGLY TO THE ISSUE.

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/167
