### ISSUE TITLE
Death Knight -  unholy, gargoil pet not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#293]
Current behavior: the pet you summon dose 0 dmg

How it should work: the pet is supposed to deal damage.

Proof (video or image):

## DON'T FORGET TO LABEL IT A
![DK-Gargoil 0 dmg](https://user-images.githubusercontent.com/100777412/156760739-70b05616-a856-48ac-8740-4816a1c861c6.jpg)
CCORDINGLY TO THE ISSUE.

**Comment by Ragelezz** [comment]
ref https://github.com/Evolution-WoW/Bug-Report/issues/621
