### ISSUE TITLE
Death Knight- pet "leap" spell not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#294]
Current behavior: the DK has a pet and that pet has a spell called leap. When you press it the pet just runs to the target

How it should work: It supposed to make the pet jump at the target

Proof (video or image):
![DK- pet Leap not working](https://user-images.githubusercontent.com/100777412/156761105-7f50de5b-63dc-47cf-bf82-856c5c9e9afa.jpg)

**Comment by Ragelezz** [comment]
ref https://github.com/Evolution-WoW/Bug-Report/issues/621
