### ISSUE TITLE
Mage- frost artefect spell no working as it should

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#295]
Current behavior: the spell works but, it's supposed to give you a brain freeze proc

How it should work: dmg +  brain freeze proc

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![mage artefact spell](https://user-images.githubusercontent.com/100777412/156764448-7719010e-489e-4806-acc4-eec8c2cdd6d8.jpg)

**Comment by Ragelezz** [comment]
proof of that? already doing that.
