### ISSUE TITLE
Mage - Incanters flow not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#298]
Current behavior: it's not giving any stacks no matter how much u cast or deal dmg

How it should work: while in combat it builds stacks up to 20% then decreases to 4%, rotates every 10 seconds 

Proof (video or image):

![incanters flow](https://user-images.githubusercontent.com/100777412/156770144-0ac7fa0a-7cf2-4e55-ad9a-28e7c09206a4.jpg)

**Comment by Hauntspectre** [comment]
Fixed.
