### ISSUE TITLE
Mage- frost bomb deals no dmg

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#299]
Current behavior: you can apply the debuff but there is no dmg  

How it should work: it should deal dmg when you hit the target with icelance

Proof (video or image):
![frost bomb](https://user-images.githubusercontent.com/100777412/156783698-16773031-1b72-4b6a-afa0-797af610d305.jpg)

**Comment by Hauntspectre** [comment]
Reviewing.

**Comment by Hauntspectre** [comment]
Fixed.
