### ISSUE TITLE
[Game crash]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#303]
Current behavior:
While you have levitate on and try to use fly path the game crashes for you 
How it should work:
It shouldn't crash, it should take you to the location you chose and levitate should stay on you. 
Proof (video or image):
https://imgur.com/f6my2Z8

+Also zooming in and out in the flight map while choosing the flight point crashes your game.

**Comment by Ragelezz** [comment]
more to confirm ? can't reproduce (aswell for zooms)

**Comment by Infinity19o** [comment]
https://imgur.com/qV5XWjQ 

Dissable the addons worked, it didn't crash for me.

**Comment by Infinity19o** [comment]
Fixed.
