### ISSUE TITLE
[Paladin][Protection]Blessed Hammer

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#304]
Current behavior: Debuff and Animation not applying

How it should work: Throws a Blessed Hammer that spirals outward, dealing (10% of Attack power) Holy damage to enemies and reducing the next damage they deal to you by (Attack power * 30 / 100). (should be 12% reduce damage) Mematoru i cant find the radious of the spell but i suggest for the start if possible add the same radious as for Consacration

Proof (video or image):

**Comment by Mematoru** [comment]
Fixed.
