### ISSUE TITLE
[Paladin][Retribution]Holy Power Generators

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#305]
Current behavior: Not applying . 

How it should work: Crusader Strike (35395) 1 holy power, Blade of Justice (184575) 2 holy power , Arcane Torrent (155145) 1 holy power 

Proof (video or image):

**Comment by Mematoru** [comment]
Reviewing.

**Comment by Ragelezz** [comment]
fixed @Mematoru
