### ISSUE TITLE
[Rogue] Seal Fate Passive

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#308]
Current behavior: it doesn't work

How it should work: when you critically strike with a melee attack that generate combo points , you gain an additional combo point per critical strike wich means , when you mutilate a target it usually awards 2 combo points if you don't crit with it , if you crit only with main hand for example you should get 3 cp and if you hit with both of them you should get 4 cp , Toxic blade should award 2 combo points when you crit with it  , also garrote aswell 2 cp if you crit when you apply it on target!

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed
