### ISSUE TITLE
[Paladin][Spell] Light of Dawn does not heal (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#31]
**Current behavior:**
At the moment Light of Dawn does not heal at all.

**How it should work:**
The spell should heal up to 5 allies in a 15yd frontal cone.

Proof (video or image):

https://user-images.githubusercontent.com/100310056/155519119-97ee9588-c82b-4159-8d90-858350bcd729.mp4

**Comment by Ragelezz** [comment]
fixed
