### ISSUE TITLE
Lava Burst proc lost

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#33]
Current behavior: When having a Lava burst proc while casting Lava burst, the proc is lost

How it should work: Proc should not be lost

Proof (video or image): Doesn't happen all the time

**Comment by Ragelezz** [comment]
actually i think its intended
remember when i did leveling on SL and i had procs while casting that procced spell, proc was consumed even tho i casted
need a retail test on this.

**Comment by Denimz92** [comment]
Lava Surge proc now remains even when casting other spells, works as intended.
