### ISSUE TITLE
[Warlock] Demonic Empowerment

### ISSUE THREAD

**Issue by Ragelezz** [Evolution-WoW/Bug-Report#34]
Current behavior:
it energizez the caster instead of the current demon summoned
How it should work:
it should energize the demon not the caster
Proof (video or image):

**Comment by Ragelezz** [comment]
fixed

**Comment by zlu372** [comment]
The spell empowers your target instead of affecting all summoned demons. It doesn't provide the HP increase or the damage increase. Only haste increase is present.
