### ISSUE TITLE
[Paladin][Talent] Judgement of Light does not heal (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#37]
**Current behavior:**
At the moment, the **Judgement of Light** debuff does not heal the attacker, even though the stacks are consumed by the attack. Also **Crusader Strike** resets/applies the debuff on target,

**How it should work:**
When applying the **Judgement of Light** debuff on a target, any attacking ally should be healed by each consumed stack of the debuff. Also, the debuff should only reset/reapply by Judgement.

**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155523702-c246f3f0-c7a1-47ab-ab0a-bd7549f2650e.mp4

**Comment by Mematoru** [comment]
Reviewing.

**Comment by Mematoru** [comment]
Fixed.
