### ISSUE TITLE
Earthen Rage passive no additional damage

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#38]
Current behavior: While having Earthen Rage talent and damaging a target, no additional damage is done to the target (visuals included)

How it should work: https://wow.zamimg.com/uploads/screenshots/normal/413833.jpg

Proof (video or image):

![image](https://user-images.githubusercontent.com/16610472/155523476-3f2feb03-7c18-4a09-9b65-e0c17d636cb2.png)

**Comment by Ragelezz** [comment]
fixed
