### ISSUE TITLE
[Warlock] Seed of Corruption

### ISSUE THREAD

**Issue by Ragelezz** [Evolution-WoW/Bug-Report#44]
not working at all

**Comment by Hauntspectre** [comment]
Fixed:
- corruption is applied correctly now
- sow the seeds talents fixed
- the explosion spreads corruption to all hit targets
- the seeds detonates on dot expire, damage from another detonated seed or after the required damage to the target was done

Remaining problems: https://github.com/Evolution-WoW/Bug-Report/issues/164
