### ISSUE TITLE
[Warlock] Immolate

### ISSUE THREAD

**Issue by Ragelezz** [Evolution-WoW/Bug-Report#48]
does not apply debuff on target

also DoT doesn't generate 1 SS fragment and no 50% chance to generate additional 1 on CS

**Comment by Hauntspectre** [comment]
Revewing.

**Comment by Hauntspectre** [comment]
Fixed.

**Comment by Ragelezz** [comment]
fa issue separat pt crit si ma ocup eu mai tarziu
