### ISSUE TITLE
[Paladin][Talent] Beacon of Virtue applied on more targets than intended (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#52]
**Current behavior:**
Casting Beacon of Virtue on a target will also apply the beacon on all nearby allies.

**How it should work:**
There should be a limit of 4 beacons (target and 3 allies near the target).

**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155527912-229fc307-d905-4092-8e8f-7b0aecde58e3.mp4

**Comment by Mematoru** [comment]
Fixed.
