### ISSUE TITLE
[Mage] Arcane missiles

### ISSUE THREAD

**Issue by Hauntspectre** [Evolution-WoW/Bug-Report#532]
-No bonus damage
- Arcane missiles  refreshed the charge - may be correct? Needs research

**Comment by Humpi96** [comment]
Each damaging spell cast has a 15% chance to activate  Arcane missiles.
Chance doubled for Arcane Blast.
Max 3 charges.
And i don;t think that arcane missiles dmg is suposed to give you a refresh on the charge, that way it would be spamable and the spell would be abused.

**Comment by Ragelezz** [comment]
fixed
