### ISSUE TITLE
[Paladin][Talent] Divine Purpose not working 

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#54]
**Current behavior:**
Divine Purpose does not proc. (only tested on Holy since the Retri holy power spenders are not working)

**How it should work:**
For Holy spec, when using Holy Light or Light of Dawn, you should have a 15% chance to receive the Divine Purpose buff that makes it so the mentioned spells do not start their cooldown and can be used instantly.

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed (retri aswell)
