### ISSUE TITLE
[Paladin][Talent] Light's Hammer does not heal/damage (Holy)

### ISSUE THREAD

**Issue by Minem24** [Evolution-WoW/Bug-Report#55]
**Current behavior:**
At the moment Light's Hammer does no damage/heal.

**How it should work:**
The spell should heal up to 6 allies in the spell area or damage enemies in the area, every 2 seconds for 14 seconds.

**Proof (video or image):**

https://user-images.githubusercontent.com/100310056/155582987-2abfa357-29cc-4047-a94a-9a3dfbc0a3c8.mp4

**Comment by Mematoru** [comment]
Healing/Damage fixed. Reviewing the target cap.

**Comment by Mematoru** [comment]
Fixed.
