### ISSUE TITLE
[Monk][WW] Storm,Earth and Fire 

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#575]
Current behavior: summoning clones out of combat , they just stand there and you cant fixate them on other targets
   also Not copying the abilityes

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
so they can be summoned only while on combat?

**Comment by Harakyri** [comment]
No you can summon them anytime in and out of combat , just if you stummon them before you get in combat with the target , they wont do anything

**Comment by Ragelezz** [comment]
ref here https://github.com/Evolution-WoW/Bug-Report/issues/621
