### ISSUE TITLE
[Warlock][Demonology] Soul Harvest

### ISSUE THREAD

**Issue by zlu372** [Evolution-WoW/Bug-Report#579]
Current behavior: The spell doesn't increase the pets damage by 20% nor does the Doom stacking increase its duration. In addition, the buff initially without Doom on any targets start of from 11 seconds and decreases, when it should be starting from 12 and increasing by 4 seconds for each target that has Doom on it, up to 36 seconds.

**Comment by zlu372** [comment]
Tested it with other specs as well, the agony won't increase the duration for Affliction and due to Immolate not being applicable it's impossible to test if it's broken for Destro as well.

**Comment by Ragelezz** [comment]
fixed
