### ISSUE TITLE
[Warlock]Grimoire of Service

### ISSUE THREAD

**Issue by zlu372** [Evolution-WoW/Bug-Report#594]
Current behavior: When choosing this talent you do no receive it in your spellbook. If you drag and drop it to your action bars right from the talent book, you're only provided with Grimore: Felguard, which shouldn't be possible for neither Affliction or Destruction. Grimoire: Felguard should only be available to Demonology. Regardless, the spell is not usable in any case. 

Tested this one as Affli and received Felguard.

**Comment by Ragelezz** [comment]
fixed, felguard will still appear but cannot be summoned, main spell on spellbook fixed aswell
