### ISSUE TITLE
[Warlock] Demonic Circle

### ISSUE THREAD

**Issue by zlu372** [Evolution-WoW/Bug-Report#595]
Current behavior: Whilst setting down the circle works fine, porting back to it is not possible as the ability is not functional and gives out a message 'You can't do that yet'

**Comment by zlu372** [comment]
Ok so there's another actually quite big issue, the moment you place down your Demonic Circle you aren't able to use any of your spells. Not just Demonic Circle to port back to where the player created it in the first place. It completely locks your spells from using them.

**Comment by Ragelezz** [comment]
fixed
