### ISSUE TITLE
Mage- frost- thermal void talent

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#599]
Current behavior: The talent gives you the 10 extra secondnd on icy vains, but it's not extending the duration of icy vains by 1 second when you hit a target that is frozen or fingers of frost proc.

How it should work: hitting frozen targets whit icelance or icelance with fingers of frost prock should give you 1 extra second on icy vains. very big dmg booster in frost mage rotation.

Proof (video or image):
![Thermal Void](https://user-images.githubusercontent.com/100777412/157062153-e704deb0-24dd-45a9-973d-3423ebcf7289.jpg)

**Comment by Hauntspectre** [comment]
Duplicate.
