### ISSUE TITLE
Mage - fire - [Hot Streak] not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#600]
Current behavior: Critting will not give you a [Hot Streak] buff.

How it should work: 2 direct dmg critical hits in a row makes ur next pyroblast/flamestrike instant and doble the ignite dmg

Proof (video or image):
![HOT STREACK](https://user-images.githubusercontent.com/100777412/157065950-2d245108-c4c8-42ca-9948-765f81c057c3.jpg)

**Comment by Hauntspectre** [comment]
Duplicate.
