### ISSUE TITLE
Mage - fire- Cinderstorm not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#601]
Current behavior: dose no dmg just passes trough the tharget

How it should work: it should deal dmg in an arc, bonus dmg if target is ignited

Proof (video or image):
![Cinderstorm](https://user-images.githubusercontent.com/100777412/157068850-46f19081-dfd1-4e30-8bd0-5436961567bf.jpg)

**Comment by Hauntspectre** [comment]
Duplicate.

**Comment by Ragelezz** [comment]
duplicate
