### ISSUE TITLE
Mage -arcane - [Arcane Missiles] self dmg

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#602]
Current behavior: when you cast [Arcane Missiles] you dmg your self

How it should work:

Proof (video or image):
![self dmg missiles](https://user-images.githubusercontent.com/100777412/157071194-aaf21be4-f4ec-41fb-b325-67cd81dd4088.jpg)

**Comment by Ragelezz** [comment]
fixed
