### ISSUE TITLE
Mage - arcane - [Presence of Mind]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#603]
Current behavior: [Presence of Mind] stacks are consumed by any spell.

How it should work: you receive 2 stacks of [Presence of Mind] and they need to be consumed only by arcane blast not by any other spell. 

Proof (video or image):

![presence](https://user-images.githubusercontent.com/100777412/157073306-674d825f-0c87-4830-8913-f66de154f3be.jpg)

**Comment by Ragelezz** [comment]
fixed
