### ISSUE TITLE
Mage -fire- [Firestarter]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#604]
Current behavior: not working.

How it should work: 100% critical hit when target is above 90% hp

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![WoWScrnShot_030722_181835](https://user-images.githubusercontent.com/100777412/157074225-93fbdc3a-b1b2-45a6-a93b-59c05f5e0aaa.jpg)

**Comment by Hauntspectre** [comment]
Fixed.
