### ISSUE TITLE
Druid- restoration - [Balance Affinity] not working as it should

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#607]
Current behavior: [Balance Affinity] dose not give you the spells it should( moonkin, starsurge, lunar strike) and it dose not gives you 5 yard range extra on spells

How it should work:

Proof (video or image):

## DON'T FORGET TO LABEL 
![WoWScrnShot_030822_165232](https://user-images.githubusercontent.com/100777412/157262931-ffab7bc1-bb1b-4bea-be54-5495ecbb20bf.jpg)
IT ACCORDINGLY TO THE ISSUE.

**Comment by Humpi96** [comment]
[Feral Affinity] and [Guardian Affinity] also not working as they should

**Comment by Ragelezz** [comment]
fixed all 3
