### ISSUE TITLE
Druid - restoration - [Efflorescence] not working

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#608]
Current behavior: [Efflorescence] dose not heal at all

How it should work: healing over time to 3 injured allies

Proof (video or image):
![WoWScrnShot_030822_165833](https://user-images.githubusercontent.com/100777412/157263761-21a0c1fa-9f67-430c-8a94-683eebad1e93.jpg)

**Comment by Ragelezz** [comment]
"injured allies"
not self
