### ISSUE TITLE
log in

### ISSUE THREAD

**Issue by florinkirito** [Evolution-WoW/Bug-Report#609]
Current behavior: i`m loging in on wow with set portal on wow evolution
this is writed in the wtf file , just this : SET portal "logon.wow-evolution.com" and then i enter the game and i get this : SET realmList "logon.warmane.com"

How it should work: what should i write? to log in on your server?

Proof (video or image): https://i.postimg.cc/Pf8fzsxp/set-portal.png
https://i.postimg.cc/NM2t4mgq/set-2.png

**Comment by florinkirito** [comment]
i do that but its the same

**Comment by Ragelezz** [comment]
delete file, enter game, check config again and set only portal.
