### ISSUE TITLE
[Rogue][Subtlety] Nightblade tooltip incorrect

### ISSUE THREAD

**Issue by Ired-Evolution** [Evolution-WoW/Bug-Report#613]
Current behavior: Nightblade's tooltip shows that it deals 1 damage every 2s.

How it should work: The tooltip should show the appropriate damage dealt every 2s.

Proof (video or image): 
![image](https://user-images.githubusercontent.com/70637889/157377080-012f36da-f06a-4a00-bedd-589b0c5cf98a.png)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/40
