### ISSUE TITLE
[Rogue][Subtlety] Master of Subtlety

### ISSUE THREAD

**Issue by Ired-Evolution** [Evolution-WoW/Bug-Report#614]
Current behavior: The talent aura is not applied to you after breaking stealth - But it is applied whilst in stealth.

How it should work: You're supposed to deal 10% incr. damage whilst in stealth AND for 5 seconds after breaking stealth

Proof (video or image):
![image](https://user-images.githubusercontent.com/70637889/157378179-bc329953-b6a2-4533-a8e6-072213befe7a.png)

**Comment by Mematoru** [comment]
Fixed.
