### ISSUE TITLE
[Rogue][Subtlety] Nightstalker

### ISSUE THREAD

**Issue by Ired-Evolution** [Evolution-WoW/Bug-Report#615]
Current behavior: It currently only increases move speed, but it does not incr. damage by 12% while in stealth.

How it should work: It should increase both move speed by 20% and damage dealt by 12% whilst stealthed / use Shadow Dance(technically stealthed).

Proof (video or image):
![image](https://user-images.githubusercontent.com/70637889/157378487-b7a4eb9c-4e1b-4c8e-bf82-812dc2f29d61.png)

**Comment by Mematoru** [comment]
Fixed.
