### ISSUE TITLE
[Rogue][Subtlety] Shadow Dance

### ISSUE THREAD

**Issue by Ired-Evolution** [Evolution-WoW/Bug-Report#616]
Current behavior: It applies a visual aura on your character, but nothing else.

How it should work: It should place you in "stealth", so you're able to use abilities otherwise only usable in stealth such as "Shadowstrike", as well as grant all combat benefits such as damage incr. from various talents.

Proof (video or image):

**Comment by Ragelezz** [comment]
its working, you can use shadowstrike for 8 seconds after casting shadow dance
