### ISSUE TITLE
[Rogue] Cheat Death

### ISSUE THREAD

**Issue by Ired-Evolution** [Evolution-WoW/Bug-Report#617]
Current behavior: Does not proc

How it should work: Should set players health to 7% of Max. Health after receiving a fatal attack, and give a 85% damage reduc. taken for 3 sec. afterwards -- cannot proc more than once per 6 min.

Proof (video or image):

**Comment by Ired-Evolution** [comment]
Needs re-test(was done via dying to fall damage - needs to be tested by getting killed by an actual attack as well)

**Comment by Ragelezz** [comment]
fixed
