### ISSUE TITLE
[Hunter Artifacts]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#627]
**Beast Master Artifact:** 
It doesnt summon Hati only 1 pet active. 
Proof: 
https://imgur.com/ZO6UKh0
https://imgur.com/pD104gR

**Marskmanship Artifact:** 
Windburts does not apply 50% speed to allies no wind trail either also Vulnerable cannot be applied.
Proof: 
https://imgur.com/VYv7Jsy
https://imgur.com/MKuyMoG
https://imgur.com/undefined

**Comment by Mematoru** [comment]
Fixed.
