### ISSUE TITLE
[Mage] Mirror Image

### ISSUE THREAD

**Issue by Ragelezz** [Evolution-WoW/Bug-Report#68]
not working

**Comment by Ragelezz** [comment]
fixed

**Comment by RadenSlayer1** [comment]
Currently Mirror Image are having the incorrect cast logic -> 

How it is currently working - Whenever the Mirror Image is casted they pick a random target and start attacking it without having caster in combat.

How it should work - 
Whenever the Mirror Image is being casted without having the caster in combat it should stand idle and follow the caster until the caster has started their cast or engaged combat by receiving any sort of hit.

As well whenever the caster has traveled a specific distance away from Mirror Image they should follow the player, currently they are continously tunneling on the adds.

![image](https://user-images.githubusercontent.com/13876686/160478056-7995015e-5f52-46d1-bd6c-d44087cabf22.png)

**Comment by RadenSlayer1** [comment]
Currently the only way to apply the correct logic for the Mirror Image behaviour is by -> 

Casting - 
1. [Greater Invisibility]
2. [Mirror Image]

**Comment by Ragelezz** [comment]
fixed
