### ISSUE TITLE
Druid- balance - Lunar empowerment

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#682]
Current behavior: Sunfire consumes the Lunar empowerment buff

How it should work:  Lunar empowerment should only be consumed by Lunar Strike

Proof (video or image):

![Lunar](https://user-images.githubusercontent.com/100777412/158175632-1cf88a8a-9be1-47ec-b8c1-960de06286d1.jpg)

**Comment by Mematoru** [comment]
Fixed.
