### ISSUE TITLE
Druid - balance - [Force of Nature]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#683]
Current behavior: [Force of Nature] just summons the minions but they are not attacking

How it should work: The summoned minions should attack and taunt the enemy

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![WoWScrnShot_031422_145651](https://user-images.githubusercontent.com/100777412/158176562-4348a6fd-8312-4a73-a43e-31c0ab470b0e.jpg)

**Comment by Ragelezz** [comment]
fixed
