### ISSUE TITLE
Druid - balance - [Warrior of Elune]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#684]
Current behavior: the [Warrior of Elune] buff is consumed by other spells like solar wrath 

How it should work: the buff should only be consumed by lunar strike and not other spells

Proof (video or image):
![WoWScrnShot_031422_145946](https://user-images.githubusercontent.com/100777412/158176963-ca9af03b-5ffe-433f-bab1-3650ec1509ad.jpg)

**Comment by Ragelezz** [comment]
fixed
