### ISSUE TITLE
Druid - balance - [Starlord]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#685]
Current behavior: the [Starlord] talent is not reducing any cast time 

How it should work: 20% cast time reduction to solar wrath and lunar strike when the empowerment buff is activated

Proof (video or image):

![WoWScrnShot_031422_150332](https://user-images.githubusercontent.com/100777412/158177456-86ca6f2a-9650-461a-aa6a-717f87396ecf.jpg)

**Comment by Mematoru** [comment]
Fixed.
