### ISSUE TITLE
Druid - [Wild Charge]

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#686]
Current behavior: the [Wild Charge] from moonkin form sends you forward instead of backword 

How it should work: it should make you jump away from the enemy and send you backword 

Proof (video or image):

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
![WoWScrnShot_031422_151435](https://user-images.githubusercontent.com/100777412/158179443-cf06e4fc-a20e-456a-bfba-5e7df299d727.jpg)

**Comment by Mematoru** [comment]
Fixed.
