### ISSUE TITLE
[Druid][Feral] Tiger's Fury

### ISSUE THREAD

**Issue by Trased** [Evolution-WoW/Bug-Report#69]
Current behavior: 
After using Tiger's Fury (haven't tried another dmg modifiers yet), the spells are starting to do more damage even after the buff expires, more than before, but 15% lower than the damage dealt when buff is active. That happens to all the spells on feral, the only way to deal the initial amount of damage is to relog.

How it should work:  - 

Proof (video or image):
https://streamable.com/4nsyf0

**Comment by Mematoru** [comment]
Fixed.
