### ISSUE TITLE
[Suramar Questline]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#712]
**Previous report not valid**
Continue reports under.

**Comment by Infinity19o** [comment]
> Spawn missing NPC's and recheck where you got stuck.

Will try, but I do not think that will trigger the continue ofc the questline it self.
will let you know.

**Comment by Infinity19o** [comment]
> Spawn missing NPC's and recheck where you got stuck.
Spawning NPC didn't help, can't return the quest.
Proof:
https://imgur.com/X2Vu5Wx

**Comment by Chazier1** [comment]
**Quest: Magic Message ID: 39986**  - https://www.wowhead.com/quest=39986/magic-message

~Accepting the quest works fine, but not being able to complete as the objective does not spawn where its supposed to be.

How it's supposed to work : https://www.youtube.com/watch?v=9PF2I4fH0GM&ab_channel=WoWQuests

Proof : https://imgur.com/oDFntrz

Quest: Trail of Echoes ID: 39987 - https://www.wowhead.com/quest=40009/arcane-thirst

~The portal does not spawn after accepting the quest from the NPC, which is supposed to take you to the specific zone in Suramar to start the quest. Going there in person the quest works, except that there is no speech between the mobs. 

Proof : https://imgur.com/CfFQ8ZE

~Using the Quest Item works fine, except that the animation is not existent. The purple spiral which I am supposed to click does not appear, even though the objective counts when the item is used in the specified area. After revealing all the Echoes, the speech between Thalyssra and Erasmus Moonblade does not take place, but he can be slain. 

The NPC is present to hand in the quest normally. 

How it's supposed to work : https://www.youtube.com/watch?v=suynyOWPQkc&t=56s&ab_channel=WoWQuests


**Quest: The Only Way Out is Through ID: 40008** - https://www.wowhead.com/quest=40008/the-only-way-out-is-through

~Arcanist Thalyssra leaves a duplicate behind as she starts walking. Also, the mobs that are supposed to "drain" the barrier that she has as we go further down the road do not appear. The only ones spawning straight attack you in a stacked pack. 

Proof : https://imgur.com/0Qyu3Cw

How it's supposed to work :  https://www.youtube.com/watch?v=A-gSnH4NCrE&ab_channel=WoWQuests

**The Nightborne Pact ** - https://www.wowhead.com/quest=40123/the-nightborne-pact

~The cinematic works fine. 

**Quest: Arcane Thirst ID: 40009**  - https://www.wowhead.com/quest=40009/arcane-thirst

~The quest is missing a reward which is a back slot. 

Proof : https://imgur.com/P1BnH8w

~Instantly after accepting the quest, the objective to "Search Shal'Aran"  counts instantly without having to actually go further down the cave. 

Proof : https://imgur.com/zPUAOge

~There are 2 things that has to be done after searching the cave, which is to slay Keeper Selentia and collect 6 Crystalized Ancient Mana, which can be done in the same time, but i had to kill her and then collect the orbs in order for Crystals to appear in the quest log. 

Proof : https://imgur.com/xnM2c9l
           https://imgur.com/NLlfpF9

How it's supposed to be: https://imgur.com/WTflbjU

~Also the Ancient Keepers are static and do not move unless approached whereas they should be flying around. Also the amount of damage they do is quiet big. 

Proof : https://imgur.com/re122gx

**Quest: Shal'Aran ID: 42229** - https://www.wowhead.com/quest=42229/shalaran

~Quest works fine, only seemed that the speech was off, and not at the right time, it also seemed that she has skipped one of the parts that she has to explore which is  Side Cavern Lights and went way to fast to the Bottom Lights. She also seemed to miss parts of the speech near the end of the quest. (Stopped at " I have more questions now than before" ) 

How it's supposed to work : https://www.youtube.com/watch?v=EYnsbN05REA&ab_channel=WoWQuests 

~However, the quest was completed but there were 2 NPC's ( First Arcanist Thalyssra), one at the entrance of the cave and the one that we searched the cave with. The quest could only be turned in at the entrance of the cave. 

Proof : https://imgur.com/swm9BZ7 
           https://imgur.com/aovUzzn ( Entrance NPC ) 

**Quest: Ancient Mana** ID: 44672   - https://www.wowhead.com/quest=44672/ancient-mana

~ Quest works just fine. 

**Quest: Oculeth's Workshop ID: 40011** - https://www.wowhead.com/quest=40011/oculeths-workshop

~Worked just fine. 

**The Delicate Art of Telemancy** ID : 40747 -  https://www.wowhead.com/quest=40747/the-delicate-art-of-telemancy 

~There are 2 NPC's, one inside the ruins and one outside in front of one of the portals. 

Proof : https://imgur.com/sU9krdC
           https://imgur.com/k99PVyA

~Using and collecting the quest items work just fine, the only problem is that in the zones where you are teleported the mobs spawn stacked in 2s one on top of another. 

Proof :  https://imgur.com/MCBAMcv
             https://imgur.com/f3SqZGU
             https://imgur.com/EcRjTeK

~Collecting Ancient Mana from the mobs, gives this stacked pop up which can be quiet frustrating as it fills up the whole screen 

Proof : https://imgur.com/15iyzKx

**Quest: Network Security** ID: 40748   - https://www.wowhead.com/quest=40748/network-security

~The quest worked just fine. 

**Quest: Close Enough** ID : 40830 - https://www.wowhead.com/quest=40830/close-enough

~ Oculeth's body can be found in front of the cave on the rock, however when picked up it disappears but it counts as picked. Going near Thalyssra she starts interacting as if i have the body on me and completed the quest. 

Proof : https://imgur.com/aykx5sy
            https://imgur.com/YjoDYEg

**Quest: Hungry Work** ID: 44691  - https://www.wowhead.com/quest=44691/hungry-work
 
~Quest works just fine ( Minor Note: When giving the quest in, "Warp Walking" is supposed to be shown as a reward, which it doesn't) - Does not affect the quest in any way.

**Quest: Survey Says...** ID: 40956 - https://www.wowhead.com/quest=40956/survey-says

~ Quest works just fine. 

**Quest: An Old Ally ID: 40012** - https://www.wowhead.com/quest=40012/an-old-ally

~ Quest works. 


To be continued...

**Comment by FiuryMan** [comment]
> Quest: Magic Message ID: 39986 
![WoWScrnShot_041122_234420](https://user-images.githubusercontent.com/93371178/162829005-07212f8d-36ab-4054-89e8-7245ee27f74d.jpg)
![WoWScrnShot_041122_234459](https://user-images.githubusercontent.com/93371178/162829018-a19adbde-2a33-4886-b0ed-4b1331d93911.jpg)


>Trail of Echoes ID: 39987
![WoWScrnShot_041122_234557](https://user-images.githubusercontent.com/93371178/162829270-543c5f09-01ec-4bb0-a310-c9eeb553d8de.jpg)

>Quest: A Re-Warding Effort ID : 41149
Fixed the display of the NPC.

>Quest : Blood of My Blood ID : 41989 
Fixed the reward.

> After reading the grave, there are 2 mobs spawning, 1 attacks straight away and 1 has the speech and then attacks. (they are both duplicates)
![image](https://user-images.githubusercontent.com/93371178/162832929-0a4bba11-66d3-44eb-9de7-b48e6aed3d8b.png)

Works fine

>Randomly being attacked constantly by something invisible and it can t be targeted.

Can't reproduce the issue. more info pls.

**Comment by FiuryMan** [comment]
The "duplicate" npc is a phasing thing, hard to fix, no reason to focus on that.

**Comment by FiuryMan** [comment]
The npc falling through map bugs were fixed at the same time for all the npc's when we changed the maps configurations

**Comment by Thale94** [comment]
Special Delivery - (id 40947) Npc is not giving me the quest
https://imgur.com/a/9EGCbee

All Along the Waterways - (id 40727) Npc is not giving me the quest, npc should give me both quests but it gives me only "Redistribution" quest.

Little One Lost - (id 42486) After completing the quest, the Npc Korine "Veren's Daughter" is following me everywhere (i completed like 10/15+ quests and still following me)
https://imgur.com/a/ZhF5hve

Silkwing Sabotage - (id 42836) Npc not giving the quest, can't continue the questline
https://imgur.com/a/10b8LiA

The Perfect Opportunity - (id 43309) Quest is not completing when arriving to location
https://imgur.com/a/W7Su4NI

In the Bag - (id 43317) Npc not giving the quest
https://imgur.com/a/1zqhQ8E

Court of Stars: Beware the Fury of a Patient Elf - (id 43314) Npc not giving the quest
https://imgur.com/a/RMW4ypg

The Shardmaidens - (id 43360) after i took the quest "Fragments of Disaster" i should be able to take the quest "The Shardmaidens" also but i couldn't, and after i finished "Fragments of Disaster" the Npc didn't gived me "The Shardmaidens" anymore
https://imgur.com/a/39OuDbd

Flow Control and Ephemeral Manastorm Projector - (id 43564 - 43563) You should be able to take both quests from npc but after taking 1 of them you can't take the other one also and after finishing the one you have taken, the npc doesn't give the other quest anymore
https://imgur.com/a/U2DXlsE

Precious Little Left - (id 40967) Npc not giving the quest, can't continue the story
https://imgur.com/a/I0bzSdZ

You've Got to Be Kitten Me Right Meow - (id 41197) The quest is not working as it should, i mean you just walk by the baby kittens and it count as you deliver the kittens, you don't even need to click on them.

Managazer - (id 41480) Npc not giving the quest, you should be able to take all 3 quests from the npc but i could take only 2 "Natural Adversaries and Moonwhisper Rescue" and after i finished this 2 quests the npc didn't give me "Managazer" anymore and i couldn't continue the questline without it.

Band of Blood Brothers - (id 40320) Npc not giving the quest
https://imgur.com/a/iA35XUM

https://imgur.com/a/KH7kNA2

**Comment by FiuryMan** [comment]
>Special Delivery - (id 40947) Npc is not giving me the quest
>https://imgur.com/a/9EGCbee
Fixed

>All Along the Waterways - (id 40727) Npc is not giving me the quest, npc should give me both quests but it gives me only >"Redistribution" quest.
Fixed

>Silkwing Sabotage - (id 42836) Npc not giving the quest, can't continue the questline
>https://imgur.com/a/10b8LiA
Fixed 

>The Perfect Opportunity - (id 43309) Quest is not completing when arriving to location
>https://imgur.com/a/W7Su4NI
After you click on the NPC, the quest should get completed.
![image](https://user-images.githubusercontent.com/93371178/163234015-ab623ee7-b960-48d6-ac99-8e864d331aa5.png)

>In the Bag - (id 43317) Npc not giving the quest
>https://imgur.com/a/1zqhQ8E
Fixed


>The Shardmaidens - (id 43360) after i took the quest "Fragments of Disaster" i should be able to take the quest "The >Shardmaidens" also but i couldn't, and after i finished "Fragments of Disaster" the Npc didn't gived me "The Shardmaidens" >anymore
>https://imgur.com/a/39OuDbd
Fixed

>Flow Control and Ephemeral Manastorm Projector - (id 43564 - 43563) You should be able to take both quests from npc but >after taking 1 of them you can't take the other one also and after finishing the one you have taken, the npc doesn't give the >other quest anymore
>https://imgur.com/a/U2DXlsE
Fixed

>Precious Little Left - (id 40967) Npc not giving the quest, can't continue the story
>https://imgur.com/a/I0bzSdZ
Fixed

>Managazer - (id 41480) Npc not giving the quest, you should be able to take all 3 quests from the npc but i could take only 2 >"Natural Adversaries and Moonwhisper Rescue" and after i finished this 2 quests the npc didn't give me "Managazer" >anymore and i couldn't continue the questline without it.
>
>Band of Blood Brothers - (id 40320) Npc not giving the quest
>https://imgur.com/a/iA35XUM
Fixed
