### ISSUE TITLE
[Highmountain questline] Faction quests

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#720]
![image](https://user-images.githubusercontent.com/16610472/161845422-a88d75e1-2b8a-4c0e-a1d6-a3d0aba9bac3.png)

**Comment by Ragelezz** [comment]
Keepers of the hammer - id 38907 can't gossip to Warbrave Oro > you need to complete https://www.wowhead.com/quest=39733/the-lone-mountain before this quest, no problem here 
Poisoned Crops - id 39272, cannot destroy posioned crops (cannot progress The Rivermane Tribe story) > this one works fine, no gm on testing, only with .gm off.
Ormgul the Pestilent - id 39491, no loot for the quest item (cannot progress The Rivermane Tribe story) > worked fine aswell after killing the npc.
Fish out of Water - id 39614, can't interact with fishes > worked fine, clicked the fishes and after a couple of seconds they give credit
The Underking comes - id 42104, can't interact with villagers to evacuate > use quest item, Horn of Jale, extra button.

**Comment by Ragelezz** [comment]
Riverbend storyline
Grasp of the Underking - id 39025, is not available at Spiritwalker Ebonhorn (id 93805) after The Underking comes (id 42104) is completed
The Drogbar - id 39026, is not available at Spiritwalker Ebonhorn (id 93805) after The Underking comes (id 42104) is completed
![Uploading WoWScrnShot_040422_204340.jpg…]()

**Comment by Ragelezz** [comment]
Rocs vs Eagles - id 38910, can't free Captive Great Eagles > they flee after you interact with them and give 1 q credit, all good

**Comment by Ragelezz** [comment]
The Skies of Highmountain - id 39387, can't interact with Lasan Skyhorn > no issues here,
![Uploading WoWScrnShot_040422_210333.jpg…]()

**Comment by Ragelezz** [comment]
The Story of Huln - id 40167, can't gossip with Spiritwalker Ebonhorn > its working fine

**Comment by Ragelezz** [comment]
Huln's War - The Arrival - id 39983, can't gossip with Spiritwalker Ebonhorn > working

**Comment by Ragelezz** [comment]
The Path of Huln - id 39575, can't gossip with Spiritwalker Ebonhorn > all good+escort q working

**Comment by Ragelezz** [comment]
An Ancient Secret - id 39577, Defend Huln combat scene does not trigger
The Backdoor - id 39579, awards the meta achiev checkmark for the storyline before it finishes
both working ok, meta achieve is triggered when you complete it now

**Comment by Ragelezz** [comment]
Wax On, Wax Off - id 39765, doesn't drop quest item > all good
Candle of Command - id 40339, can't interact with object > all good
Burn the Candle at Both Ends - id 40345, can't interact with chair object > all good
Can't Hold a Candle To You - id 39772, invisible wall blocks you for progression > fixed

**Comment by Ragelezz** [comment]
Neltharion's Lair: Death to the Underking - id 39781, cannot talk to Navarrogg to finish the quest > fixed

**Comment by Ragelezz** [comment]
Highmountain Stands - id 42512, Dargul cannot be attacked > its autocomplete

**Comment by Denimz92** [comment]
Balance of Elements - id 39488, auto-complete

**Comment by Denimz92** [comment]
Spawned Warbrave Oro for completition for Keepers of the Hammer

**Comment by Denimz92** [comment]
Balance of Elements - id 39488, Violent Crageater (95916) don't drop Empowered Crystal, only Drogbar Manathirster (95866)

**Comment by Denimz92** [comment]
The Skyhorn Tribe - id 38913, not awarded by Mayla Highmountain (93826)

**Comment by Denimz92** [comment]
Oakin Ironbull (95256) - doesn't award Witch of the Wood (39372), Hags of a Feather (39373) & An Audience with Torok (39374)

**Comment by Denimz92** [comment]
Spawned Stonedark Drogbar (96286) for Rite of Blood quest.

**Comment by Denimz92** [comment]
Rock Troll in a Hard Place - id 39381, quest giver is also quest ender. You need to gossip with Stonedark Drogbar(96286) instead of Navarrogg (95421). Also, wrong Navarrogg is highlighted for the quest (95259). Unphased Stonedark Drogbar(96286) is set to be visible for other players after it dissapears for current player (needs recheck after rr).

**Comment by Denimz92** [comment]
Blood Debt - id 39426, Stonedark Drogbar is spawned twice
![image](https://user-images.githubusercontent.com/16610472/161828140-10b8b6f5-2e1f-452a-b969-2eeba7d9b8dd.png)

**Comment by Denimz92** [comment]
The Skyhorn Tribe - id 38913, cannot turn in at Lasan Skyhorn (93841)

**Comment by Denimz92** [comment]
Justice rains from above - id 40594, needs complete rework (vehicle skills don't do damage, boulderfist ability counts towards quest progression, totem walks after vehicle, quest progress is too slow)

**Comment by Denimz92** [comment]
The Underking - id 39780, npc (97266) is under the map with the whole scene (area suffers changes)
![image](https://user-images.githubusercontent.com/16610472/161838975-7c403477-8ed8-46ed-a034-df4f7210319c.png)

**Comment by Denimz92** [comment]
Secrets of Highmountain - id 38916, added to Spiritwalker Ebonhorn (98825)

**Comment by Denimz92** [comment]
Added Highmountain Spiritwalker npc (108069) for In Defiance of Deathwing - id 40219

**Comment by Denimz92** [comment]
Spawned Vision of Deathwing (97056) for Titanic Showdown (39578)

**Comment by Denimz92** [comment]
To See the Past - id 40520, Darkshard Crystal falls through map

**Comment by FiuryMan** [comment]
> Balance of Elements - id 39488, increase chance drop for Empowered Crystal (128393) for all Violent Crageater (95916) & Drogbar Manathirster (95866)

Fixed, set 50% drop chance.

> The Skyhorn Tribe - id 38913, not awarded by Mayla Highmountain (93826)

> Oakin Ironbull (95256) - doesn't award Witch of the Wood (39372), Hags of a Feather (39373) & An Audience with Torok (39374)

> Rock Troll in a Hard Place - id 39381, quest giver is also quest ender. You need to gossip with Stonedark Drogbar(96286) instead of Navarrogg (95421). Also, wrong Navarrogg is highlighted for the quest (95259).

Fixed the chain for  > The Skyhorn Tribe >The Bloodtotem Tribe , if the chain is broken somewhere else, reply here.



> Justice rains from above - id 40594, needs complete rework (vehicle skills don't do damage, boulderfist ability counts towards quest progression, totem walks after vehicle, quest progress is too slow)

Sent the issue to a spell-developer.
