### ISSUE TITLE
[Quest][Legion] In the Blink of an Eye

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#724]
Quest 44184 - Dalaran teleportation gossip is not done by the NPC 111109 (Emissary Auldbridge)

**Comment by Denimz92** [comment]
Deadwind Pass Khadgar doesn't do the Dalaran teleportation 
![image](https://user-images.githubusercontent.com/16610472/160698138-e24ff8af-b600-47d6-a41c-2424cd93b9d1.png)

**Comment by Trased** [comment]
![image](https://user-images.githubusercontent.com/93371178/161424056-f1610aea-0eb9-43e6-9d9c-b430ee9183c4.png)

Fixed.
