### ISSUE TITLE
[Stormheim questline] Faction quests

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#727]
Horde:
The Splintered Fleet - id 39801, Cinematic not implemented error (quest is doable)

Stormheim quests:
A Trial of Might - id 39594, nothing happens after interacting with the object
No Wings Required - id 38613, auto-complete
Another Way - id 38617, Dread-Rider Cullen spawns multiple times & keeps following you on the map
Cry Thunder! - id 38624, auto-complete

**Comment by Ragelezz** [comment]
Supplies From the Skies - id 38036, can't turn in quest, npc under map - respawned but might persist > its ok now

**Comment by Ragelezz** [comment]
To Light the Way - id 39849, npc goes through texture, can't loot > fixed
Assault and Battery - id 38053, can't loot npc, falling through map > fixed

**Comment by Ragelezz** [comment]
The Final Judgement - id 38818, no credit for killing Runeseer Faljar > no issue, you don't need to kill him but to get him to a %hp.

**Comment by Ragelezz** [comment]
Stormheim's Salvation - id 40005, God-King Skovald cannot be targeted > pvp system issue... turn your pvp on and its working, known issue even by blizzard, https://www.reddit.com/r/wow/comments/t4ikkc/you_cannot_do_that_to_a_pvp_target_while_pvp_is/
https://us.forums.blizzard.com/en/wow/t/you-cannot-do-that-to-a-pvp-target-while-pvp-is-disabled-in-a-dungeon/425295/3

**Comment by Ragelezz** [comment]
Pump it up - id 38358, containment buff and device UI remains displayed on the screen even after completing the quest (buff cannot be removed) - .unaura 181970 > it disappeared after a few seconds

**Comment by Ragelezz** [comment]
Allies in Death - id 39851, can't interact with npc's > drowning valkyra are the correct npcs for credit, not others, works fine

**Comment by Ragelezz** [comment]
Impalement Insurance - id 38615, cannot destroy harpoon launcher when interacting with object (object dissapears after) > it gives you credit when clicking the harpoon and disappears, no issue

**Comment by Ragelezz** [comment]
The Aegis of Aggramar - id 43349, cannot place the Aegis in The Portrait Room > no issue, working

**Comment by Ragelezz** [comment]
Stormheim - id 39864, credit for "Travel to Dalaran" not granted, use .q complete
Stormheim - id 39864, credit for "Travel to Dalaran" not granted, use .q complete
both versions worked for me on different chars, no issue (H and A)

**Comment by FiuryMan** [comment]
A Royal summons -id 38035, spawned quest giver, criteria for "The Skyfire boarded" not awarded
Quest working for me. 
![image](https://user-images.githubusercontent.com/93371178/162582013-f16d65f4-eb6a-4ff0-977c-470abec6ef99.png)

**Comment by FiuryMan** [comment]
Lightning Rod - id 38058, npc's out of range no questbar progress - when completed it's rewarded twice 
-- After the maps fix, the quest is working properly need to fix just the double reward thing
![image](https://user-images.githubusercontent.com/93371178/162582195-997d67d0-e90e-43d2-ad38-6577938c2dfd.png)

**Comment by FiuryMan** [comment]
Making the Rounds --- You just have to wait for Sylvanas to do the script. quest working.
![image](https://user-images.githubusercontent.com/93371178/162584841-1264fe63-fc95-442f-b0d3-ad89523c41e4.png)

**Comment by FiuryMan** [comment]
Stormheim Salvation --
![image](https://user-images.githubusercontent.com/93371178/162585303-8a587829-0842-4955-b954-aece8fc17a93.png)
![image](https://user-images.githubusercontent.com/93371178/162585323-663fd62f-c4e6-4740-97e8-4be5f8815288.png)

**Comment by FiuryMan** [comment]
*Waking the Shieldmaiden - id 38815, Ashildir spawns twice

Fixed.
