### ISSUE TITLE
Mage - Shimmer

### ISSUE THREAD

**Issue by RadenSlayer1** [Evolution-WoW/Bug-Report#735]
Current behavior: Shimmer is currently ignoring any collision letting player blink through/within walls/objects.

How it should work: It should not ignore collision.

Proof (video or image):
![image](https://user-images.githubusercontent.com/13876686/160475867-203d88d4-6f40-4b27-b4ce-bc378421f929.png)

**Comment by Ragelezz** [comment]
vmaps issue, #8

**Comment by acidmanifesto** [comment]
I'll give you a hint.
It isn't vmaps.
