### ISSUE TITLE
Issues pre/during - " The battle of broken shores" 

### ISSUE THREAD

**Issue by Chazier1** [Evolution-WoW/Bug-Report#739]
1. Using blink, either while on the bridge or before(but landing on it)  will teleport you right under it.

Proof : https://imgur.com/WGPvHz3

2. Soon after starting the battle of broken shores scenario, the text from one of the NPC's seems to be of a different language which i believe it's Russian?

Proof : https://imgur.com/yLWKIkB 

3.  At stage 6, when you have to attack the legion forces, using one of the catapults, the enemies would evade the attacks and only few be damaged for a very small number. The NPC's that are with you will randomly attack mobs dealing considerate damage whereas you would still not be able to help.  After dying and going back to the zone where the assault was taking place i've attacked mobs around, still dealing barely any damage to them and they would suddenly die at around 90% of their health.

Proof : https://imgur.com/H7qjJhM

4. Soon after leaving the catapult, i was being attacked by the mobs whereas out of the sudden i got one shot by one of the mobs. 

Proof : https://imgur.com/iRl2IZa

**Comment by Ragelezz** [comment]
1 fixed
2 i have a separate bug report for that, looking
3 an 4, can't reproduce, check again please and if its the case again, open new report.
