### ISSUE TITLE
[Pandaren Starting zone] The Lesson of the Iron Bough

### ISSUE THREAD

**Issue by FiuryMan** [Evolution-WoW/Bug-Report#746]
Current behavior: Currently the quest is marked as "daily" but you can redo the quest infinite ammount of times, but after you take / complete the next quest, you cannot take it anymore.

How it should work: This should be a normal quest that you need to complete once to progress through pandaren starting zone.

Proof (video or image):
https://imgur.com/MfxvWob

**Comment by Ragelezz** [comment]
moved to legacy
