### ISSUE TITLE
[Goblin Starting Zone]

### ISSUE THREAD

**Issue by Mematoru** [Evolution-WoW/Bug-Report#747]
[Quest] Rolling with my Homies - you are not able to pick up Izzy, Ace and Gobber
https://i.imgur.com/v1Sq8wW.png

**Comment by Mematoru** [comment]
[Quest] Necessary Roughness/ [Quest] Fourth and Goal - both get considered as completed if you enter Bilgewater Buccaneer

**Comment by Mematoru** [comment]
https://www.wowhead.com/npc=37106/coach-crosscheck is untargetable

**Comment by Mematoru** [comment]
After you reach The Lost Isles, if you relog, you get the Near Death! debuff and it will not go away, making you unable to move.

**Comment by Denimz92** [comment]
Goblins will be auto teleported to Orgrimmar, thus skipping the start zone.
