### ISSUE TITLE
[Quest][Legion] A Falling Star

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#748]
Current behavior: NPC Archmage Khadgar missing and can't turn in the quest.

How it should work:

Proof (video or image): 
![Q](https://user-images.githubusercontent.com/100341575/161037767-9faef85f-c93d-433e-950e-f572d01777f9.jpg)

**Comment by Trased** [comment]
![image](https://user-images.githubusercontent.com/93371178/161425402-37273b4d-49fc-40fb-bb2c-89db86e4f317.png)

Fixed.
