### ISSUE TITLE
[Quest+Scenario][Legion] Bringer of the Light

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#752]
Current behavior: Bringer of the Light - id 44004 Portal to Exodar Scenario missing
Bringer of the Light Scenario - after defeating High General Rakeesh, can't use Khadgar's Beacon to teleport to Daralan.

How it should work:

Proof (video or image):

**Comment by FiuryMan** [comment]
Tested just now, everything worked fine. Can you retest please and take some screenshots if you encoutner the bugs?
