### ISSUE TITLE
[Death knight][Class Hall + Artifact] Quest starter

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#755]
Current behavior: Member of the Order not triggering 

How it should work: Once you enter Dalaran for the first time after Legion launches, you will be approached by a representative from your class. The quest will send you on the chain to acquire your first artifact weapon for your chosen specialisation. Once you have obtained your artifact and completed the questline, you will unlock your class order hall. The questline is impossible to miss, since it is part of your natural progression through the Legion expansion.

Proof (video or image):

**Comment by Mematoru** [comment]
I believe this is a general issue since finished the Broken Shore part on Priest and Rogue and the NPC that spawns when you enter Dalaran never showed up.

**Comment by Ragelezz** [comment]
hackfixed
