### ISSUE TITLE
Bug Quest ”Demons Among Us ”

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#756]
Current behavior: You can't complete the quest at npc.

How it should work : -

Proof (video or image): 
![Annotation 2022-03-31 203910](https://user-images.githubusercontent.com/102504567/161126860-00ddd310-00ef-422a-811a-fb5c418c684d.png)

**Comment by Infinity19o** [comment]
Npc does spawn but he fall thru map.

**Comment by Ragelezz** [comment]
fixed
