### ISSUE TITLE
Bugs Storyline Azsuna

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#757]
(All npc appear if you give gm on !)
Ex: 1 random quest 
Gm off :![Annotation 2022-03-31 230152](https://user-images.githubusercontent.com/102504567/161149797-fad1184e-6e07-4c60-bf4c-4f3009ba02d0.png)
Gm on: ![Annotation 2022-03-31 230638](https://user-images.githubusercontent.com/102504567/161149890-e4563a5f-b94a-4a9c-a67b-c2ae1b149e0b.png)

Chapter 1 : ”Behind Legion Lines”

”Paradise Lost”
You don't have npc to complete the quest!

”Down to Azsuna”
You can't complete the quest , npc does not appear!

”Into the Fray” 
You can not give complete to the quest!

Chapter 2: ”Defending Azurewing Repose”

”The Death of the Eldest”
You don't have npc to complete the quest!

”Agapanthus”
You can not start the quest , is not npc!

**Comment by Trased** [comment]
The Issues described above have been fixed. I have completed the full storyline of Azsuna, the only missing bug is on quest [The Right Weapon for the Job](https://www.wowhead.com/quest=37565/the-right-weapon-for-the-job) that you can't use [Pile of Weapons](https://www.wowhead.com/item=118330/pile-of-weapons) in the cave so you can progress through the quest.

**Comment by Ragelezz** [comment]
Actually the item works fine but ingame client sees you in another area rather than Oceanus Cove (even if you see on map Oceanus cove) 
in case area: old coast path 
outside cave where ships at oceanus cove, you have plenty of npcs there, npcs from cave removed.
