### ISSUE TITLE
[Demon Hunter Class Campaign+Artifact] Questline

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#758]
Artifact
Vengeance: Vengeance Will Be Ours (Scenario) - in Last phase when collecting [Aldrachi Warblades] the weapons are automatically added in your bag but also appear as a loot to be looted and the quest is not completing

Havoc: Call of the Illidari - Npc not there (Kayn Sunfury), can't complete the quest. (Npc Kor'vas Bloodthorn not spawning near me to give the quest)
The Power to Survive - Can't select which Artifact i want to choose after accepting the quest
Making Arrangements - Npc not giving the quest / not working
The Hunt (Scenario) - Not working, the scenario is not starting

Class Hall Campaign

Enter Vigil - Npc not there / quest is not completing after gliding to Illidari Redoubt
Securing the Way - The quest is not completing

Unbridled Power - Npc not there, can't turn in the quest
Spoils of Victory - Npc not giving the quest / Npc disappearing (Phasing)

Direct Our Wrath - The quest should not be auto completed
Return to the Fel Hammer - Npc not there
Rise, Champions - Npc not giving the quest

Move Like No Other - The Sneaky Imp Npc is falling under the map / when inspecting the Crate inside the Wonderworks nothing happens / when finding the imp inside the Scribe's Sacellum (Sanctuary) the Imp is dead and can't continue with the quest

Confrontation at the Black Temple (Scenario) - Npc's falling under the map and can't go to confront Akama / Scenario not working

Vault of the Wardens: Vault Break-In - Not getting the quest automatic after completing the previous quest "Strange Bedfellows"

One Battle at a Time - Npc not giving the quest
Jump-Capable - Portal at Felsoul Hold (Optional) (Legion Portal missing) 
The Invasion of Niskara (Scenario) - Stage 1 "Commence Bombardment aiming to the sky can't move to aim

**Comment by Ragelezz** [comment]
map issues and scouting map quests fixed, recheck (already edited the post but recheck the rest)

**Comment by FiuryMan** [comment]
>Enter Vigil - Npc not there / quest is not completing after gliding to Illidari Redoubt

![image](https://user-images.githubusercontent.com/93371178/163431852-16e68ae2-4095-41fe-b3b1-72c1eb20041f.png)

>Unbridled Power - Npc not there, can't turn in the quest

![image](https://user-images.githubusercontent.com/93371178/163433138-22fed8e6-4cfb-46cb-bff9-8df767626c9d.png)
![image](https://user-images.githubusercontent.com/93371178/163433191-bb6afdf1-c299-41c9-81fe-f1fc6c8b512f.png)

>Spoils of Victory - Npc not giving the quest / Npc disappearing (Phasing)

![image](https://user-images.githubusercontent.com/93371178/163433382-109bd8b6-e9bb-4bcf-85c3-59f2f6328fb4.png)

>Direct Our Wrath - The quest should not be auto completed

![image](https://user-images.githubusercontent.com/93371178/163433646-a664d3f2-e532-4cf5-8aab-e13b14d9ca16.png)

It is not.

>Return to the Fel Hammer - Npc not there

Npc in class hall is giving you the quest.
![image](https://user-images.githubusercontent.com/93371178/163434034-792b3060-30f9-41f7-b115-4af57a456186.png)

>Rise, Champions - Npc not giving the quest

![image](https://user-images.githubusercontent.com/93371178/163434313-9767df47-6c5c-4ba1-af70-29e0b52adaba.png)

>Move Like No Other - The Sneaky Imp Npc is falling under the map / when inspecting the Crate inside the Wonderworks nothing happens / when finding the imp inside the Scribe's Sacellum (Sanctuary) the Imp is dead and can't continue with the quest

![image](https://user-images.githubusercontent.com/93371178/163435782-ee0f34e9-a0df-4737-abdd-16b5155edafb.png)

>Confrontation at the Black Temple (Scenario) - Npc's falling under the map and can't go to confront Akama / Scenario not working

![image](https://user-images.githubusercontent.com/93371178/163436686-dda91814-6b5a-480a-9f27-c31670180560.png)


>Vault of the Wardens: Vault Break-In - Not getting the quest automatic after completing the previous quest "Strange Bedfellows"

![image](https://user-images.githubusercontent.com/93371178/163437790-24279e0b-34b6-4950-9033-2a6a43c44b68.png)

>One Battle at a Time - Npc not giving the quest

Fixed.

>Jump-Capable - Portal at Felsoul Hold (Optional) (Legion Portal missing)

Fixed.

>The Invasion of Niskara (Scenario) - Stage 1 "Commence Bombardment aiming to the sky can't move to aim

We are looking into it.

**Comment by Thale94** [comment]
Quest Securing the Way - (id 42872) I can't complete the quest because i can't do what the quest is asking me to do (most probably because the gateway is already spawned and can be used already).
https://imgur.com/a/L6sovwh

After reaching level 103 to be able to take the quest "The Blood of Demons" i am also able to take the quest "Securing Mardum" which i should not be able to take at this point because this quest is available later on the campaign and only after completing the quest "Working With the Wardens"
https://imgur.com/a/TOR3tdo

Working With the Wardens - (id 42731) Npc not giving me the quest (npc id 108782), the quest available in the screen shot is the next quest after this one which i mentioned the issue above
https://imgur.com/a/pabBEBw

Rune Ruination - (id 42736) i should be able to take all 3 quests at the same time to complete them, not 1 by 1, and after completing the first 2 rune quests "Ragnar's Rune and Floki's Rune"(id's 42738, 42739) i can't take the next quest "Rollo's Rune" (id 42737), without it i can't complete the main quest "Rune Ruination"
https://imgur.com/a/TBnnhWt
https://imgur.com/a/P6NePyW

Preparations for Invasion - (id 42669) Npc not giving the quest
https://imgur.com/a/srTfPHU

One Battle at a Time - (id 44694) Npc not giving the quest
https://imgur.com/a/C36eC5D

**Comment by FiuryMan** [comment]
>Quest Securing the Way - (id 42872) I can't complete the quest because i can't do what the quest is asking me to do (most probably because the gateway is already spawned and can be used already).
https://imgur.com/a/L6sovwh

Fixed.

>After reaching level 103 to be able to take the quest "The Blood of Demons" i am also able to take the quest "Securing Mardum" which i should not be able to take at this point because this quest is available later on the campaign and only after completing the quest "Working With the Wardens"
https://imgur.com/a/TOR3tdo

Fixed.

>Working With the Wardens - (id 42731) Npc not giving me the quest (npc id 108782), the quest available in the screen shot is the next quest after this one which i mentioned the issue above
https://imgur.com/a/pabBEBw

The npc is giving the quest after completing the previous quest -> Unexpected Visitors (id 42131)
![image](https://user-images.githubusercontent.com/93371178/163925962-e8e38f46-d9fa-470c-b135-cc67a8294fc6.png)

>Preparations for Invasion - (id 42669) Npc not giving the quest
https://imgur.com/a/srTfPHU

The npc is giving the quest after completing prev quest -> Two Worthies id 42776
![image](https://user-images.githubusercontent.com/93371178/163926714-fab8e114-7eb4-4900-b8cf-09ba49467d48.png)

>Rune Ruination - (id 42736) i should be able to take all 3 quests at the same time to complete them, not 1 by 1, and after completing the first 2 rune quests "Ragnar's Rune and Floki's Rune"(id's 42738, 42739) i can't take the next quest "Rollo's Rune" (id 42737), without it i can't complete the main quest "Rune Ruination"
https://imgur.com/a/TBnnhWt
https://imgur.com/a/P6NePyW

Fixed.

>One Battle at a Time - (id 44694) Npc not giving the quest
https://imgur.com/a/C36eC5D

Fixed.
