### ISSUE TITLE
[Scouting Map]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#762]
Current behavior: Can't see the missions on the Scouting Map

How it should work:

Proof (video or image): 
![image](https://user-images.githubusercontent.com/100341575/161281776-d235e84d-23fe-4e00-adf9-37c89a32da4b.png)

**Comment by Ragelezz** [comment]
beacuse you don't have any missions available at that time, its working.
![WoWScrnShot_033122_153710](https://user-images.githubusercontent.com/69433539/161282072-00758a67-1163-4a3c-8f86-c27d6f9379e8.jpg)

**Comment by Thale94** [comment]
I couldn't do any quest from class hall where i have to do missions on scouting map, none of them where visible.
