### ISSUE TITLE
[Shaman] Class hall campaign

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#763]
https://www.wowhead.com/class-hall-campaign-for-the-third-artifact-relic-guide#shaman

A Ring Unbroken (id 39746) - must gossip with NPC/vehicle 103728 to fly to Maelstrom (Maelstrom Dalaran portal not working - object 251311) - .go c id 96528
The Elements Call - window is empty since the artifacts are already given in the inventory
The Coming Storm - 43334,  nothing happens when entering vehicle
The Codex of Ra - 43338, criteria for Travel to Guo-Lai Halls not awarded (spawned everything else missing for the quest)
Recruiting The Troops - 42142, progress time not shown at NPC, training option appears 3x times

Further Advancement - 46781, autocomplete
Expanding Your Horizons - 43945, autocomplete
Your Fullest Potential - 44006, autocomplete
Ma'haat the Indomitable - 42989 autocomplete
Wavespeaker's Trail - 43645, not working (not found when .q reward)
To the Deeps - 43644, no criteria when in Vashj'ir (not found when .q reward)

**Comment by Ragelezz** [comment]
scouting map issues fixed, recheck

**Comment by Denimz92** [comment]
The Ritual of Tides - working now
Summoner Morn - 
![image](https://user-images.githubusercontent.com/16610472/162606253-9f142774-6b06-4e98-b8d5-fb8b2f4cf96a.png)
but cannot turn in
Mission: Investigating Deepholm - in progress
Return to the Firelands - in progress
Enemies of Air - in progress

**Comment by Ragelezz** [comment]
Both Destroying the Cult(41777) & The Master's Plan (41897) cannot be taken at once from Muln Earthfury (106001)
Both Unleashing the Elements (41898) & Held Captive!(41899) cannot be taken at once from Muln Earthfury (106001) - they are given one after another 
this is intended

**Comment by Ragelezz** [comment]
Rise, Champions - 42383, criteria for Champion: Stormcaller Mylra (quest 42198) not awarded, npc doesn't give the quest- fixed

**Comment by Ragelezz** [comment]
The Voice of Thunder - 39771, not awarded, doesn't have completition criteria when you reach the temple-worked, no issue

**Comment by FiuryMan** [comment]
>A Ring Unbroken (id 39746) - must gossip with NPC/vehicle 103728 to fly to Maelstrom (Maelstrom Dalaran portal not working - object 251311) - .go c id 96528

You had wrong npc spawned, it was just a trigger. I spawned the correct one.

>The Elements Call - window is empty since the artifacts are already given in the inventory

Fixed.

>The Coming Storm - 43334, nothing happens when entering vehicle
The Codex of Ra - 43338, criteria for Travel to Guo-Lai Halls not awarded (spawned everything else missing for the quest)

The artifact chains has been removed as you get all the artifacts at lvl 100. Ignored.

>Recruiting The Troops - 42142, progress time not shown at NPC, training option appears 3x times

The time is shown, fixed the gossip.
![image](https://user-images.githubusercontent.com/93371178/164053928-364753e1-a852-482a-bf80-d6ac8296ad27.png)

>Further Advancement - 46781, autocomplete

Fixed.

>Expanding Your Horizons - 43945, autocomplete
Your Fullest Potential - 44006, autocomplete

Intended.

>Ma'haat the Indomitable - 42989 autocomplete

https://www.wowhead.com/quest=42989/mahaat-the-indomitable#videos:id=116642

>Wavespeaker's Trail - 43645, not working (not found when .q reward)
To the Deeps - 43644, no criteria when in Vashj'ir (not found when .q reward)

Artifact questlines are disabled.
