### ISSUE TITLE
[Item] Cannot be equipped

### ISSUE THREAD

**Issue by YserasChosen** [Evolution-WoW/Bug-Report#764]
Current behavior: After I finished the quest [To Be Prepared] I tried to equip [Signet of Stormwind] and it's not working.

How it should work: The item should be equipped on a ring slot.

Proof (video or image):

![image](https://user-images.githubusercontent.com/102521982/161351295-9bd69f27-f1cc-4010-a9f4-4306c7408511.png)

**Comment by Ragelezz** [comment]
was fixed
