### ISSUE TITLE
[Quest] The Battle for Broken Shore

### ISSUE THREAD

**Issue by YserasChosen** [Evolution-WoW/Bug-Report#765]
Current behavior: I tried to do the questline but I'm stuck at stage 8/9 because Krosus can't be damaged.

How it should work: https://www.youtube.com/watch?v=GkUYiQ3h_Lc&ab_channel=Astewir

Proof (video or image):
![image](https://user-images.githubusercontent.com/102521982/161353466-0da3225d-a538-4e8e-be4e-b5c1ef847420.png)

**Comment by Ragelezz** [comment]
can't reproduce, i see that fordring is not even killed so he cannot be attacked until fordring is not dead.
