### ISSUE TITLE
Quest log full error

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#767]
Quest log full error with only 4 quests in the quest log.

![image](https://user-images.githubusercontent.com/16610472/161378657-f19b0a81-6f9c-4a75-8057-650f0df28339.png)

**Comment by Infinity19o** [comment]
And you can't accept more quests or is it a visual bug?

**Comment by Denimz92** [comment]
No more quests can be accepted.

**Comment by Ragelezz** [comment]
can't reproduce :-?

**Comment by Infinity19o** [comment]
Same, I have multiple quests atm and still accepting more. 
@Denimz92 can you try to accept more quests on that character ?

**Comment by Infinity19o** [comment]
Can't reproduce.
