### ISSUE TITLE
[NPC] Skyfire Gryphoon Rider & Skyfire Gryphoon

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#768]
NPC states need to be fixed (non-attackable & spawned on the ground).
91414 & 91881
![image](https://user-images.githubusercontent.com/16610472/161379322-b847e3d9-9783-4313-aaec-76368930bb09.png)
![image](https://user-images.githubusercontent.com/16610472/161379393-6225b50f-32a9-4c17-b82f-500b6f275759.png)

**Comment by Ragelezz** [comment]
they anim as dead so its okay, you cannot attack them anyway
