### ISSUE TITLE
[NPC] Vault Guardian cannot be targeted

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#770]
NPC 96282 cannot be targeted

![image](https://user-images.githubusercontent.com/16610472/161385000-13ab969f-ef3d-4245-af93-fc1f7e5944ce.png)

**Comment by Ragelezz** [comment]
npc is neutral to me and not even spawned ingame, whats with it ?

**Comment by Denimz92** [comment]
Fixed
