### ISSUE TITLE
Emmisary quests auto-complete

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#771]
Might be only in Stormheim, other zones need to be rechecked.

![image](https://user-images.githubusercontent.com/16610472/161385789-7a35a279-2a44-4d7d-94b4-d79d4c97c31b.png)

**Comment by Ragelezz** [comment]
(2017-03-28): Added.
https://wowpedia.fandom.com/wiki/Emissary_system 
paragon quests, added later, disabled for now
