### ISSUE TITLE
[Azsuna quest] NPC Multiplies

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#779]
Current behavior: While doing the quests "Fel Machinations " and "Saving Stellagosa" the NPC multiplies

Proof (video or image): 
![image](https://user-images.githubusercontent.com/100341575/161392127-b8967688-bdd6-4e70-b61f-17b92cd8243b.png)

**Comment by Thale94** [comment]
The Npc's from Quest "[You Scratch My Back...]" they're multiplying too
![image](https://user-images.githubusercontent.com/100341575/161394177-20c049e1-bcc2-41db-8a3d-9af7c856f58b.png)

**Comment by Ragelezz** [comment]
someone fixed them meanwhile, if the issue reappears, reopen issue
