### ISSUE TITLE
[Emmisary quests] Too many active

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#780]
Current behavior: There are 6 active Emissary quests while there should be a maximum of 3

Proof (video or image): 
![image](https://user-images.githubusercontent.com/100341575/161392670-8bdeb8a3-d357-4384-90f3-2ffb4ec3433e.png)

**Comment by Ragelezz** [comment]
Check from tomorrow if it happens again.

**Comment by Thale94** [comment]
It didn't happen to me anymore. It looks fine.

**Comment by Ragelezz** [comment]
if it reoccurs, reopen
