### ISSUE TITLE
[Achievement] [Fashionista tabard , shirt etc]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#781]
Current behavior: Apparently all the items collected are counting for all the Achievements Fashionista (if i collect chest piece it will be added for tabard / shirt etc. also)

Proof (video or image): 
![image](https://user-images.githubusercontent.com/100341575/161394711-4850cb00-2a4f-4956-9771-a5af1eb36bfe.png)
![image](https://user-images.githubusercontent.com/100341575/161394757-e185ed71-9c37-4c30-8e04-c30b6f7a6e58.png)
![image](https://user-images.githubusercontent.com/100341575/161394769-d0b2ceb7-c5c7-404f-a726-08e591daa216.png)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/16
