### ISSUE TITLE
[NPC]Quest An Urgent Gathering(id 38710) End Quest

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#783]
Current behavior:  lord maxwell tyrosus id 90369 not spawned 

How it should work:

Proof (video or image):

**Comment by Trased** [comment]
![image](https://user-images.githubusercontent.com/93371178/161425653-0ed0648e-93fe-4698-8513-45ce35771ccc.png)
Fixed.
