### ISSUE TITLE
[Mobs] Can't be attacked by players

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#789]
Current behavior: If you go in Suramar , there are mobs where you can't attack them but if you go close enough they attack you , the thing is i can't sap them , nor attack them , it says invalid target ! (i also believe these are not the only ones behaving like this)

How it should work:

Proof (video or image): https://prnt.sc/Ee4KjrjHRnl4

**Comment by Trased** [comment]
The mobs from the screenshot has been fixed. If you encouter same issue with other NPC's , add them here, don't create new issue, will leave the post open

**Comment by Ragelezz** [comment]
reopen bug report if its the case.
