### ISSUE TITLE
[Quest]A Light in the Darkness 43700

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#793]
Current behavior: the portal you need to take is phased in front of the priest class hall portal 

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
what portal?

**Comment by Harakyri** [comment]
Deci ar trebui sa fie un portal ca acel de priest classhall dar daca iti
dai gm on iti apare in fata , e fazat

**Comment by Ragelezz** [comment]
imi arati acasa ca nu vad unde zici, da-mi ping pe discord

**Comment by Denimz92** [comment]
Confirmed

**Comment by FiuryMan** [comment]
Fixed
