### ISSUE TITLE
Dungeon Court of Stars 

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#794]
Missing lamp for boats that wear you at the beginning of the dungeon !

![Annotation 2022-04-03 152442](https://user-images.githubusercontent.com/102504567/161430377-75fa0f9c-ec9e-46e5-923e-a2444230211d.png)

**Comment by Trased** [comment]
Post the issue to the main topic. https://github.com/Evolution-WoW/Bug-Report/issues/692
