### ISSUE TITLE
[Druid class hall campaign]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#798]
Current behavior: 
Malorne's Refuge - Npc not giving the quest, can't start the campaign (it may be affected by getting all 4 artifact weapons without completing the artifact questlines)
Teensy Weensies! - Npc not giving the quest, can't continue the campaign
The Cycle Continues - there are not enough Critters and not respawning or respawn time is to long, can't complete the quest
Champion: Mylune - Npc Missing
The Emerald Nightmare: - can't complete the quest because when i teleport to Xavius i fall under the map (platform is bugged)
(all the quests with Scouting Map have the same issue as the other classes / no active missions

**Comment by Ragelezz** [comment]
Malorne's Refuge - invalid, i could take the quest.

**Comment by Ragelezz** [comment]
Teensy Weensies! - Npc not giving the quest, can't continue the campaign > fixed

**Comment by Malefique96** [comment]
Weapons of Legend - You can t select an artifact weapon to pursue.

**Comment by Ragelezz** [comment]
The Cycle Continues - there are not enough Critters and not respawning or respawn time is to long, can't complete the quest > added more critters

**Comment by Ragelezz** [comment]
Champion: Mylune - Npc Missing > its spawned near the scouting map

**Comment by Ragelezz** [comment]
The Emerald Nightmare: - can't complete the quest because when i teleport to Xavius i fall under the map (platform is bugged) > teleport is not available to players, we'll see when the raid is open
for scouting map: https://github.com/Evolution-WoW/Bug-Report/issues/816
