### ISSUE TITLE
[Druid class hall phasing issues]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#799]
Current behavior: Scouting Map - phasing issue
![image](https://user-images.githubusercontent.com/100341575/161550708-4ad3a637-9f32-4174-b835-bce44b84fbca.png)
Seed of Ages - phasing issue
![image](https://user-images.githubusercontent.com/100341575/161550806-f36723ee-b573-4c79-b7f0-a5b40029a15b.png)
Malorne statue - phasing issue
![image](https://user-images.githubusercontent.com/100341575/161551110-32892ea8-aaa1-4cbb-9f17-ff40f69f4c59.png)

**Comment by Ragelezz** [comment]
fixed
