### ISSUE TITLE
VMaps not working - pets, totems, blink as mage etc might fall under texture if solid ground is present

### ISSUE THREAD

**Issue by Carrysmatic** [Evolution-WoW/Bug-Report#8]
Current behavior: You can attack mobs through texture and cannot loot if killed 

How it should work: - 

Proof (video or image):

https://user-images.githubusercontent.com/100289156/155325831-548268b0-686d-44c2-a3b7-0de5252db43a.mp4

https://user-images.githubusercontent.com/100289156/155326060-dbe5ee93-4d5b-4b50-a1d9-a7839c83d501.mp4

**Comment by Ragelezz** [comment]
also reff:
https://github.com/Evolution-WoW/Bug-Report/issues/262
https://github.com/Evolution-WoW/Bug-Report/issues/224

**Comment by Ragelezz** [comment]
fixed creatures which are falling through the map
todo: LoS, spell position calculations for spell with leap/charge/blink effects.

**Comment by Ragelezz** [comment]
fixed
