### ISSUE TITLE
Mage- time warp

### ISSUE THREAD

**Issue by Humpi96** [Evolution-WoW/Bug-Report#801]
Current behavior: after casting time warp you get the bonus haste for 1 spell the it's gone

How it should work: get 30% haste for 40 sec 
![WoWScrnShot_040422_182001](https://user-images.githubusercontent.com/100777412/161577024-b5402d6f-3424-4628-b49e-b74c61c5ba8f.jpg)

Proof (video or image):

**Comment by Ragelezz** [comment]
invalid
