### ISSUE TITLE
Ingame mail from Customer Support

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#804]
After obtaining & unequipping any artifact on any class, you get ingame mail from Customer Support with missing artifact offhands

![image](https://user-images.githubusercontent.com/16610472/161608030-24586078-4fb5-4e11-bebb-a59b76776751.png)

**Comment by Ragelezz** [comment]
can't reproduce at all in my case, tried on shaman

**Comment by Denimz92** [comment]
It's related to the fact that you have the item in the inventory already but you still do the scenario to obtain it, that's why it comes via mail, so no issue.
