### ISSUE TITLE
Hunter class hall random trigger

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#807]
While questing in Highmountain for Crystal Fury & Balance of Elements cave, you get the Hunter's class hall debuff and get teleported to Nesingwary's Retreat

![image](https://user-images.githubusercontent.com/16610472/161737176-9253f173-4145-491d-8575-3e6a7854e39e.png)
![image](https://user-images.githubusercontent.com/16610472/161737219-97e75708-f89a-48f5-ad93-fe39bb2270ff.png)

Debuff should be active only when in the hunter class hall, not adjacent zones (under it)

**Comment by Ragelezz** [comment]
fixrf
