### ISSUE TITLE
World quests appearing twice

### ISSUE THREAD

**Issue by Denimz92** [Evolution-WoW/Bug-Report#815]
Post here all World Quests which appear twice in the quest log
Wanted: Bristlemaul: id 44290 - Highmountain
![image](https://user-images.githubusercontent.com/16610472/161744597-e51a673f-b788-4694-8b0c-e425c7acc35c.png)
![image](https://user-images.githubusercontent.com/16610472/161744839-8f57e3f5-0095-4700-9707-f58c872bd831.png)

**Comment by Ragelezz** [comment]
https://www.wowhead.com/quest=44290/wanted-bristlemaul#comments
https://www.wowhead.com/quest=41828/wanted-bristlemaul
not actually an issue but a lucky rng.. there are 2 world quests, rare occurance.
