### ISSUE TITLE
[Rogue Class Hall Campaign]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#817]
Spy vs. Spy - (id 43829) - Same issue with Scouting Map
The Bloody Truth - (id 44041) - After equipping the glasses to follow the blood trails, i cannot see the blood trails on the ground, although the quest can be completed
https://imgur.com/a/6YokuDy
Convincin' Old Yancey - (id 43841) Same issue with Scouting Map
Throwing SI:7 Off the Trail - (id 42684) Same issue with Scouting Map
Where In the World is Mathias? - (id 43469) Scouting Map issue (missing/phased)

**Comment by Ragelezz** [comment]
Honoring Success - (id 40950) (Wrong Dialog playing) The dialog starting is from the quest "The Final Shadow" and i don't get the option "Toast" to raise the glass to continue the quest > extra action button, works fine

**Comment by Ragelezz** [comment]
Delegation - (id 40996) Npc Marin Noggenfogger is phased away can't take the quest / Npc Nikki the Gossip is phased away can't finish the quest > fixed

**Comment by Ragelezz** [comment]
Return to the Chamber of Shadows - (id 43007) Npc Valeera Sanguinar not showing up to give the quest > fixed
Rise, Champions - (id 42139) Vanessa VanCleef is phased away, can't recruit her to complete the quest > fixed

**Comment by Ragelezz** [comment]
A More Wretched Hive of Scum and Villainy - (id 42140) Scouting Map missing (phased away) > appears after a couple of quests, no issue

The School of Roguery - (id 43013) Npc Lonika Stillblade missing (phased) can't train troops > ?? wrong maybe ? this npc can't train troops at all

**Comment by Ragelezz** [comment]
A More Wretched Hive of Scum and Villainy - (id 42140) Scouting Map missing (phased away) > fixed
The Big Bad Wolfe - (id 43014) Npc Nikki the Gossip is missing (phased) and also Scouting Map issue > fixed
What Winstone Suggests - (id 43015) Npc Winstone Wolfe missing (phased) > fixed

**Comment by Ragelezz** [comment]
Fancy Lads and Buccaneers - (id 43852) Npc Yancey Grillsen missing (phased) > fixed

**Comment by Ragelezz** [comment]
Noggenfogger's Reasonable Request - (id 42730) Npc Marin Noggenfogger Missing (phased) > fixed

**Comment by Ragelezz** [comment]
Deciphering the Letter - (id 42680) Raven's Eye missing (phased) from the table > its on table, no issue

**Comment by Ragelezz** [comment]
Picking a Fight - (id 37666) Npc Master Mathias Shaw missing (phased) can't turn in the quest > fixed
A Simple Plan - (id 37448) issue from above, Npc missing (phased) can't take quest > fixed
One More Thing... - (id 44215) Npc Lord Jorach Ravenholdt missing (phased) can't turn in the quest > fixed
A Hero's Weapon - (id 43422) Same issue from above, Npc Missing (same Npc) > fixed

**Comment by Ragelezz** [comment]
fixed the rest of the issues
