### ISSUE TITLE
[NPC] Grimwing <Flight Master>112511

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#822]
Current behavior: Clicking on it crashes the game  

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
it crashes because you are using gm on, without gm on everything is okay, semi-issue tho.

**Comment by Foxy19o** [comment]
No crashes happen.

**Comment by Harakyri** [comment]
Nice reply 2 bad it was made 2 months ago
