### ISSUE TITLE
[Quest] Neltharion's Lair: Braid of the Underking 43571

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#823]
Current behavior: npc 111480 needs to be spawn and also give this quest after the previous one with DarkHeart  Ticket

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
fixed, about the next quests, check order https://www.wowhead.com/class-hall-campaign-for-the-third-artifact-relic-guide#death-knight
