### ISSUE TITLE
[Class Campaign] Infused with Power

### ISSUE THREAD

**Issue by YserasChosen** [Evolution-WoW/Bug-Report#829]
Current behavior: The NPC Altar Keeper Biehn is not spawned and can't complete the quest.

How it should work: https://www.wowhead.com/quest=41047/infused-with-power

Proof (video or image): 
![image](https://user-images.githubusercontent.com/102521982/162072877-f5892c10-d6cc-4579-95d7-1a04a603b4d6.png)

**Comment by Ragelezz** [comment]
fixed
