### ISSUE TITLE
[Anti-Magic Shell ]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#832]
Anti-Magic  Shell heals you up to full hp. 
Proof:
https://imgur.com/l852CNb
https://imgur.com/9SR9ISO

**Comment by Ragelezz** [comment]
??
![WoWScrnShot_040722_085807](https://user-images.githubusercontent.com/69433539/162130322-fe7b2367-02ff-46fe-9fba-01579a8c26f8.jpg)
![WoWScrnShot_040722_085810](https://user-images.githubusercontent.com/69433539/162130328-24fe0727-f286-4646-9b11-ba1fa6088205.jpg)

**Comment by Mematoru** [comment]
Invalid.
