### ISSUE TITLE
[Raid] Emerald Nightmare 

### ISSUE THREAD

**Issue by YserasChosen** [Evolution-WoW/Bug-Report#838]
Current behavior: First problem: Cenarius has no loot
Second problem: When you jump into the vortex to be teleported to the next boss (Xavius) you just remain stuck in the air, cant log out, hearthstone, or anything. 

How it should work:

Proof (video or image): 

https://user-images.githubusercontent.com/102521982/162591242-c8d121e9-86da-4f65-831d-c9d089f15d34.mp4

https://user-images.githubusercontent.com/102521982/162591250-f357c991-e939-45ab-a133-07fd9772408e.mp4

**Comment by Ragelezz** [comment]
EN is not released yet, its in testing phase, moved into the main topic
