### ISSUE TITLE
[Quest] Repaid Debt

### ISSUE THREAD

**Issue by YserasChosen** [Evolution-WoW/Bug-Report#839]
Current behavior: NPC "Archmage Kalec" isn`t spawned.

How it should work:

Proof (video or image):
![image](https://user-images.githubusercontent.com/102521982/162591571-44e13ca6-6bf5-496e-a9e9-2923ee9f9f0b.png)

**Comment by FiuryMan** [comment]
Should be fixed after restart, retake quest and retest.

**Comment by Ragelezz** [comment]
fixed
