### ISSUE TITLE
Priest Class Hall quest bug !

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#840]
Quest Rising Shadows .
npc , phased .
![Annotation 2022-04-09 230759](https://user-images.githubusercontent.com/102504567/162591853-e88d4a27-828a-431e-8c4b-35b157627b00.png)
![Annotation 2022-04-09 230736](https://user-images.githubusercontent.com/102504567/162591861-5a7d4d08-588b-4cb3-80fa-79ddaddf9cad.png)
I did 2 , 3 quests with gm on , from him and then I remained spawnat and gm off

**Comment by Ragelezz** [comment]
fixed
