### ISSUE TITLE
Spread The Word

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#842]
![image](https://user-images.githubusercontent.com/102504567/162592733-2614e222-f73b-4226-8022-2b4653cf08aa.png)
It puts you to do the quest on the board in the class hall . It ends , a win with 99% , you complete , disappears and reappears to do it dinnou , I tried to complete it about 6-7 times .

**Comment by Ragelezz** [comment]
re-test please

**Comment by Bajboom** [comment]
![image](https://user-images.githubusercontent.com/102504567/163716935-aa5aff52-cf86-418c-946c-f5dec1283b07.png)
all its ok , now
