### ISSUE TITLE
Storyline class hall priest !

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#843]
Quest : A Light in the Darkness
You can not take the quest from npc . It does not appear and you can not continue class hall campaing! You can't even complete the quest, because Lord Maxwell Tyrosus is missing!
![Annotation 2022-04-10 140940](https://user-images.githubusercontent.com/102504567/162617373-f67fe48c-07b0-4a4f-aa3a-9a7089139196.png)

**Comment by FiuryMan** [comment]
Fixed.
