### ISSUE TITLE
[Scouting Map Issue]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#849]
Current behavior: First time when i check if i succeed the mission on scouting map it showed me that i failed but when i tried to do the next quest from class hall which needed me to do missions on scouting map, i couldn't use the scouting map anymore, every time when i click on the scouting map to do the missions it looks like in the photo from below.

Proof (video or image):
![image](https://user-images.githubusercontent.com/100341575/162635080-6638e788-a014-4542-b84d-ad9bb2b9c663.png)

**Comment by Ragelezz** [comment]
@Thale94

**Comment by Thale94** [comment]
no i didn't, but after a while (like 15/20min or so) it worked again and didn't showed like that anymore, it could have been triggered because of failing the mission, tho cache could fix it. If i encounter it again i will try with cache to see if works and not waiting again.
