### ISSUE TITLE
[Fall thru the texture]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#853]
Starting quest **Battle for Broken Shore** you fall thru the texture, you still make it to the _Broken Shore_ after couple of minutes **(the ship keeps riding towards there)** to do the quest if you dont move out of the zone of the ship. 
Proof:
https://imgur.com/MOPafYT
Proof2:
https://imgur.com/eliWjCt
https://imgur.com/Jq47mV7
After you make it to the Broken Shore you are inside-under the ship cannot get out. 
Proof3:
https://imgur.com/KdNHRB9
**_As for Proof 2 and 3 will retest it on other classes, so far its happening only on the hunter._**

AS  well as NPC's are falling thru the texture. 
Proof:
https://imgur.com/77btBCG
https://imgur.com/GtKnR6p

**Comment by FiuryMan** [comment]
Set the quest as Auto-Complete and you are not able anymore to start the scenario.
