### ISSUE TITLE
Training Dummy Paladin Class Hall

### ISSUE THREAD

**Issue by Holyborker** [Evolution-WoW/Bug-Report#862]
Current behavior:Dummy  is attacking me.

How it should work:Dummy should not attack  .

Proof (video or image):
https://prnt.sc/udWqNRiPQ77Z

**Comment by Ragelezz** [comment]
invalid, that dummy doesn't attack me back
![Uploading WoWScrnShot_041122_235115.jpg…]()

**Comment by Denimz92** [comment]
Fixed, but server crashed and didn't retest.

Works ok now
![image](https://user-images.githubusercontent.com/16610472/162941870-7559d847-a639-4746-829c-f1f3f0381995.png)
