### ISSUE TITLE
Quest Knowlege is Power Paladin Class Hall

### ISSUE THREAD

**Issue by Holyborker** [Evolution-WoW/Bug-Report#863]
Current behavior:Quest can be  picked up and  finished  and u  get Artifact Research  Notes but u cant  use  it.

How it should work:Get Note after finishing  quest and  use it for  knowledge.

Proof (video or image):
https://prnt.sc/Xkl_RBI49fSm

**Comment by Ragelezz** [comment]
compendiums and Artifact Knowledge items are currently disabled until we reach further phases. Everyone starts with AK 1 now.
