### ISSUE TITLE
Druid Class Hall quest bugs !

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#864]
Quest : Weapons of Legends 
The 5th quest of the class hall campain makes you choose a weapon with which to continue, but given that we are given the weapons before that, you can not pass the quest! 
![Annotation 2022-04-11 225747](https://user-images.githubusercontent.com/102504567/162831371-2c80328b-6819-44c5-8d3c-ae052353b579.png)
Quest : The Dreamer Returns   
The NPC is phased and you can't take the quest from it
![Annotation 2022-04-11 231134](https://user-images.githubusercontent.com/102504567/162834592-48b60a2a-ac52-4fbc-8abe-137fe76edcac.png)
![Annotation 2022-04-11 231438](https://user-images.githubusercontent.com/102504567/162834615-030dd8da-3cc8-498a-b7d8-a29e99ec362a.png)

Quest : The Seed of Ages 
npc does not have the quest to continue the storyline
![Annotation 2022-04-11 231438](https://user-images.githubusercontent.com/102504567/162835086-6041f767-ac23-46d2-8c0e-49bd4952020c.png)

Quest : Rise , Champions
Zen Bara doesn't have the quet to recruit the champion.
![Annotation 2022-04-11 232648](https://user-images.githubusercontent.com/102504567/162836393-754ec6be-9559-4577-8247-d5c614e55c12.png)

**Comment by FiuryMan** [comment]
>Quest : Weapons of Legends
The 5th quest of the class hall campain makes you choose a weapon with which to continue, but given that we are given the weapons before that, you can not pass the quest!

Will be automatically fixed on live.

>Quest : The Dreamer Returns
The NPC is phased and you can't take the quest from it

Fixed

>Quest : Rise , Champions
Zen Bara doesn't have the quet to recruit the champion.

Fixed.
