### ISSUE TITLE
[Suramar - Ancient Mana]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#866]
Current behavior: There are very few shards which give you ancient mana and it is very hard to complete some quests which require ancient mana to feed the npc's. Also the big turtles "Lowland Manashell" which also drop a lot of them are also very few only 3/4 of them.
And the shards which gives you ancient mana are only the small ones, i have never seen a big stash of ancient mana or any stash bigger then the small shard which gives you only 10 ancient mana.

**Comment by Mematoru** [comment]
Fixed.
