### ISSUE TITLE
[Suramar Insurrection Storyline]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#872]
Current behavior:
Crystal Clearing - (id 44843) Npc Sentinel Moonshade (id 115521) not giving the quest
https://imgur.com/a/CT2EV27
Powering Down the Portal - (id 44844) Same issue as the previous quest and same npc

Noressa (side quest) - Npc missing (Npc id 115951) and can't turn in the quest because of the same issue, the Npc is missing
https://imgur.com/a/sSYMJCU
Oculeth ex Machina (side chain) - (id 44873) Nothing happens when i speak with Oculeth to teleport me to Azsuna and i can't turn in the quest because i'm not getting teleported in the cave, there is no other way to get inside the cave, only by getting teleported by Oculeth (the entire quest chain is not working due to npc not teleporting me and i'm not able to continue it).

https://imgur.com/a/l51NmW9

**Comment by FiuryMan** [comment]
>Crystal Clearing - (id 44843) Npc Sentinel Moonshade (id 115521) not giving the quest
https://imgur.com/a/CT2EV27
Powering Down the Portal - (id 44844) Same issue as the previous quest and same npc

Fixed

>Noressa (side quest) - Npc missing (Npc id 115951) and can't turn in the quest because of the same issue, the Npc is missing
https://imgur.com/a/sSYMJCU

Fixed

**Comment by FiuryMan** [comment]
>Oculeth ex Machina (side chain) - (id 44873) Nothing happens when i speak with Oculeth to teleport me to Azsuna and i can't turn in the quest because i'm not getting teleported in the cave, there is no other way to get inside the cave, only by getting teleported by Oculeth (the entire quest chain is not working due to npc not teleporting me and i'm not able to continue it).

Fixed.
