### ISSUE TITLE
Stormheim  Quest Line Auto Completed 

### ISSUE THREAD

**Issue by Holyborker** [Evolution-WoW/Bug-Report#873]
Auto Quest's:

No Wings Required-auto comp
Impalement Insurance-auto comp
where dragon rules - auto comp

**Comment by FiuryMan** [comment]
![image](https://user-images.githubusercontent.com/93371178/163261536-2692d6c7-3cca-4834-a446-9b0f0348c28c.png)
>Impalement Insurance-auto comp 

It is not.

**Comment by FiuryMan** [comment]
>where dragon rules - auto comp

Works as intented. The path to top is auto and you just get teleported instead of flying to the top.

>No Wings Required-auto comp

Already reported here. https://github.com/Evolution-WoW/Bug-Report/issues/860
