### ISSUE TITLE
Stormheim Quest NPC  Buged

### ISSUE THREAD

**Issue by Holyborker** [Evolution-WoW/Bug-Report#874]
Stormheim 
Secrets Of The Shieldmaidens Storyline
NPC is  not working  whan  u click  it  too fly  too  camp  .
https://prnt.sc/cuVaijRv6qP7
https://www.youtube.com/watch?v=kKOesQOgcts&t=32s
Some  video from youtube  for that quest line .

**Comment by FiuryMan** [comment]
Fixed.
