### ISSUE TITLE
Obliterum System

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#875]
Current behavior: Currently if you use [Obliterum](https://www.wowhead.com/item=124125/obliterum) on an Crafted item it isn't upgrading it's iLvL, but you lose your Obliterum and 2 Blood of sargeras.

How it should work: each Obliterum use should Increase the iLvL of the item by 5, up to 900 (Maximum 12 uses or Maximum specified ammount by the item.)

Proof (video or image):
![image](https://user-images.githubusercontent.com/93371178/163266133-2463f497-b699-4644-bfc5-831fd3e6b788.png)
![image](https://user-images.githubusercontent.com/93371178/163266147-7d3123bd-d493-48fa-8752-e17d990ddf0c.png)
![image](https://user-images.githubusercontent.com/93371178/163266221-ea65be2f-1d4a-471d-89d3-3d28f9886f83.png)

**Comment by Mematoru** [comment]
Fixed.
