### ISSUE TITLE
[Quest]Recruitment Drive 44849

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#878]
Current behavior: odyn not giving this quest

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
moved

**Comment by FiuryMan** [comment]
you need to complete the quest https://www.wowhead.com/quest=46173/tactical-planning before.

invalid bug report.

![image](https://user-images.githubusercontent.com/93371178/164072964-24f42065-e9c4-40f5-ad76-a21d155b1021.png)
