### ISSUE TITLE
[Quest] Dk Classhall

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#879]
Current behavior: https://www.wowhead.com/quest=39757/keeping-your-edge  NPC 97111 not giving quest 
                             https://www.wowhead.com/quest=39832/plans-and-preparations NPC 93437 not giving Quest
                             https://www.wowhead.com/quest=42449/return-of-the-four-horsemen NPC 93437 not giving Quest
                             https://www.wowhead.com/quest=43264/rise-champions Champion NAZGRIM missing  
                             https://www.wowhead.com/quest=44248/champion-darion-mograine NPC  not giving Quest 
                           

How it should work:

Proof (video or image):

**Comment by FiuryMan** [comment]
Fixed.
