### ISSUE TITLE
Raids Cataclysm bugs !

### ISSUE THREAD

**Issue by Bajboom** [Evolution-WoW/Bug-Report#883]
FIRELANDS:
Lord Rhyolith : untargetable
![Annotation 2022-04-17 120248](https://user-images.githubusercontent.com/102504567/163709943-2bd02292-08cf-4a1a-a833-b6321ae08c0a.png)
Baleroc : phased , missing

![Annotation 2022-04-17 120218](https://user-images.githubusercontent.com/102504567/163709966-f5432679-d55c-4d8c-b887-d3a0965aee9e.png)
DRAGON SOUL: started by warmaster
![image](https://user-images.githubusercontent.com/102504567/163710388-ed198155-4d0e-4588-a51e-5678f2349ea5.png)

**Comment by Infinity19o** [comment]
Moved topic to:
https://github.com/Evolution-WoW/Legacy-Content-pre-Legion-/issues/7
