### ISSUE TITLE
[Mage][Fire] Grace period between fireball and pyroblast

### ISSUE THREAD

**Issue by jinginos** [Evolution-WoW/Bug-Report#886]
Current behavior:When casting a fireball and an insta cast pyroblast at the same time, if the fireball crits and the pyroblast doesn't crit the heating up buff disappears

How it should work:When casting a fireball and an insta cast pyroblast at the same time, if the fireball crits and the pyroblast doesn't crit the heating up buff should still remain.

Proof (video or image):
https://www.youtube.com/watch?v=cX4oG5GlSBE i count whenever this happens
Examples of how it should work
https://www.youtube.com/watch?v=sCdGo54rR0U&ab_channel=DyLemma
Time stamps: 2:28 2:37 2:42 2:46

**Comment by Ragelezz** [comment]
fixed
