### ISSUE TITLE
[Vault of The Wardens] Light missing

### ISSUE THREAD

**Issue by Herty1** [Evolution-WoW/Bug-Report#887]
Current behavior: When you get down by elevator by elevator there is no Light 
![Snímka obrazovky (138)](https://user-images.githubusercontent.com/103910668/163823445-42d4859f-e9d5-4a69-8c3f-402e900dcf46.png)

How it should work: There should be light spawned so you can take him 
![Snímka obrazovky (139)](https://user-images.githubusercontent.com/103910668/163823492-27984274-b08f-49a1-850d-b9cdebf84d11.png)

**Comment by Infinity19o** [comment]
Already reported. 
https://github.com/Evolution-WoW/Bug-Report/issues/697
