### ISSUE TITLE
[Mage][Fire] Blazing barrier damage reflect

### ISSUE THREAD

**Issue by jinginos** [Evolution-WoW/Bug-Report#888]
Current behavior: Blazing barrier damage reflect contributes to the hot streak fire mage mechanic. If the mage is hit and the barrier reflects a critical strike the mage receives a heating up/hot streak proc. Also, if the mage has a heating up proc and the barrier doesn't reflect a critical strike the heating up buff is lost. Basically it works just like any fire mage damaging spell that contributes to hot streak.

How it should work: Blazing barrier damage reflect shouldn't contribute to the hot streak fire mage mechanic.

Proof (video or image): 
https://www.youtube.com/watch?v=E2UCkBsA2y0

**Comment by Ragelezz** [comment]
fixed
