### ISSUE TITLE
[Broken Shore] Missing clues

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#892]
The main map should show where the quest objectives are, but it doesn't show anything. If the player doesn't already know where the objectives are, it's going to be a real challenge to complete the scenario.
![image](https://user-images.githubusercontent.com/59037069/164061012-b735c3ce-691a-4cb6-b6e9-387851989a08.png)
Reported by @Doppe

**Comment by FiuryMan** [comment]
Set the quest as Auto-Complete and you are not able anymore to start the scenario.
