### ISSUE TITLE
[Quest][Paladin Classhall] 

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#894]
Current behavior: A urgent gathering 38710 still triggering after complete
Forging new Strength 39722 - Altar of Ancient Kings is phased and you dont get the 100 artifact power to enpower your weapon
Recruiting the troops 42848 - showing i can recruit 3 times 
PORTAL TO DALARAN MISSING FROM CLASSHALL

How it should work:

Proof (video or image):

**Comment by FiuryMan** [comment]
Fixed.
