### ISSUE TITLE
[Rogue Class Hall][Quest] Honoring Success

### ISSUE THREAD

**Issue by jinginos** [Evolution-WoW/Bug-Report#898]
Current behavior: The quest currently works fine, except that instead of spawning 1 Vanessa that scales to your level it spawns the level 110 NPC with around 3 times for health. The level gap causes unnecessary difficulty
How it should work: Explained above

Proof (video or image): https://www.youtube.com/watch?v=YQ8o0i--tjU
She is barely beatable even if she dodges the blind, easily beatable if the blind lands.

**Comment by FiuryMan** [comment]
Fixed.
