### ISSUE TITLE
Sinister Strike damage not correct

### ISSUE THREAD

**Issue by Carrysmatic** [Evolution-WoW/Bug-Report#9]
Current behavior: SS should do 23 dmg but it does 14

How it should work:

Proof (video or image):
![image](https://user-images.githubusercontent.com/100289156/155329072-278891bc-3db8-4cee-b9e1-0a3dcfcbebae.png)

**Comment by Ragelezz** [comment]
how do you have that spell? i can't find it in spellbook.

**Comment by Ragelezz** [comment]
invalid, creatures have armor and thats why there's a small diference
