### ISSUE TITLE
[Class Hall] Recruiting the Troops [Paladin][Quest]

### ISSUE THREAD

**Issue by TigerFist1983** [Evolution-WoW/Bug-Report#902]
There is no object to click after troop recruited.
![WoWScrnShot_042122_173458](https://user-images.githubusercontent.com/86138081/164465837-20fda077-6c35-4cc7-b718-bffef9670109.jpg)

[https://www.wowhead.com/quest=42848/recruiting-the-troops](url)

**Comment by Ragelezz** [comment]
check after next restart
