### ISSUE TITLE
[Quest][Mage Class Hall] A Mage's Weapon

### ISSUE THREAD

**Issue by SirViperaX** [Evolution-WoW/Bug-Report#904]
Current behavior:
After completing Felstorm's Plea you can choose between 2 quests: **"A Mage's Weapon" - 41085** and **"The Dreadlord's Prize" - 41036**.  If you pick it up before "The Dreadlord's Prize" the player gets softlocked because he can't progress into the class hall campaign.

How it should work:
"A Mage's Weapon" should be a quest later.

Proof (video or image):
https://streamable.com/2sxr00

**Comment by FiuryMan** [comment]
fixed.
