### ISSUE TITLE
[Monk - Jade Serpent Statue]

### ISSUE THREAD

**Issue by lSeventhl** [Evolution-WoW/Bug-Report#910]
Current behavior: After casting Vivify / Enveloping Mist on a target, Statue of the Jade Serpent starts channeling Shooting Mist on the same target. The issue is that if I stop my Shooting Mist cast, the statue stops aswell.  If I cancel my Shooting Mist cast, Statue stops it's cast aswell. (Include the situation when I cancel my Shooting Mist cast for casting a new spell).

How it should work: The statue should continue the cast for 10 seconds after I cancel my cast / Change the target if I cast Vivify / Enveloping Mist on a new target.

Proof (video or image):

**Comment by Mematoru** [comment]
Fixed.
