### ISSUE TITLE
[Paladin][Classhall] 

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#913]
Current behavior: Forging New Strength 39722 - dont have 100 Artifact Power To empower and finish Quest
Communication Orbs 42888 -  Justicar Julia Celeste 109384 dosnt give quest 
Champion Armaments 44218 - NPC 110434 not spawned to start qeust 

How it should work:

Proof (video or image):

**Comment by FiuryMan** [comment]
>Champion Armaments 44218 - NPC 110434 not spawned to start qeust

Fixed.

>Communication Orbs 42888 - Justicar Julia Celeste 109384 dosnt give quest

Fixed.

> Forging New Strength 39722 - dont have 100 Artifact Power To empower and finish Quest

Upon creating a new character and taking the starter gear, you will get also a Mark of the Rogue that grants you AP.
