### ISSUE TITLE
[Rogue][Assassination] Venom Rush

### ISSUE THREAD

**Issue by Daphneqt** [Evolution-WoW/Bug-Report#915]
Current behavior: Venomous Wounds give 10 energy per tick of bleed on a poisoned target

How it should work: Venom Rush should add 3 energy to every proc of Venomous Wounds

Proof (video or image): https://imgur.com/mltT0SE
As you can see Garrote has a 18 second duration, ticking every 2 seconds => 9 ticks which nets 90 energy, and it should also proc 3 energy x 9 times = 27 from Venom Rush, which it doesnt ( Also Mutilate (2) and Seal Fate (9) shouldnt give any energy )

**Comment by jinginos** [comment]
The spell works as intended, Venomous wounds in  legion, by default, grants 7 energy per proc, when you are talented  the tooltipc changes automatically to 10 energy per  proc. 
![image](https://user-images.githubusercontent.com/103383472/164892704-9283cf43-b722-42fa-ba34-da3a745b8cfa.png)

regarding mutilate and seal fate, i don t know why details tells you they grant energy, for me it works fine on a level 110 char

**Comment by Daphneqt** [comment]
Ah good then
