### ISSUE TITLE
[Rogue] Shadowstep

### ISSUE THREAD

**Issue by jinginos** [Evolution-WoW/Bug-Report#917]
Current behavior: Using shadowstep on big targets that are not on a platform teleports you behind them

How it should work: Using shadowstep on big targets that are not on a platform should teleport you in front of them

Proof (video or image):
Grasping Tentacle https://www.youtube.com/watch?v=LVpO4-eglA4 (100362)
Grasping Tentacle https://www.youtube.com/watch?v=ibSCQX1u_a0 (98363)
Helya https://www.youtube.com/watch?v=UoE8yyueCs4 (96759)
More possible examples from the following patches or current:
Krosus
Garothi worldbreaker
Il'gynoth s eye (still on the platform, but teleporting behind him would insta kill the rogue i think due to being in the heart chamber)
Naraxas from  Neltharion s Lair

**Comment by Ragelezz** [comment]
spell disabled on those targets
