### ISSUE TITLE
[Ultimate Battle-Training Stone]

### ISSUE THREAD

**Issue by FiuryMan** [Evolution-WoW/Bug-Report#923]
Current behavior: The stone can be used on already lvl 25 pets, you get the error saying "Failed to Upgrade Pet" , but you lose the stone after the use.

How it should work: It shouldn't be available to use on lvl 25 pets // it shouldn't consume it when used on lvl 25 pets.

Proof (video or image):
![image](https://user-images.githubusercontent.com/93371178/164996495-0b7fa327-972a-47b4-a373-e1c022ff33b5.png)

**Comment by Mematoru** [comment]
Fixed.
