### ISSUE TITLE
[Death Knight Campaign] Rise, Champions

### ISSUE THREAD

**Issue by Ark0d** [Evolution-WoW/Bug-Report#937]
Current behavior: After completing "The Firstborn Rises" (ID: 42484), players are unable to pick up "Rise, Champions" (ID: 43264) from Highlord Darion Mograine hence the impossibility to advance with the campaign.

How it should work: Players should be given the option to receive the quest aforementioned from Mograine as soon as "The Firstborn Rises" has been completed.

**Comment by FiuryMan** [comment]
Fixed.
