### ISSUE TITLE
Quest : The Death of the Eldest ID:37853

### ISSUE THREAD

**Issue by Lawlexan** [Evolution-WoW/Bug-Report#946]
Current behavior:the mobs are hitting way to high

How it should work:you should be abble to take 4-6 mobs with no worry of dying

Proof (video or image):
![image](https://user-images.githubusercontent.com/103905717/166061068-8b92fb06-8dbe-4110-a221-efa26c2d9cc1.png)
melted me in 5-7 seconds only 4 adds 2 small scorpions and 2 big worms
also the quest loot item is pretty small,it can be increassed a little little bit

**Comment by Ragelezz** [comment]
fixed
