### ISSUE TITLE
[Paladin Class hall quest]

### ISSUE THREAD

**Issue by Thale94** [Evolution-WoW/Bug-Report#947]
Current behavior: 
Recruiting the Troops (id 42848) After i recruited the troops and waited the 30min time to be finished, the flag to recruit them is not appearing and i can't recruit them. Can't complete the quest to continue.

Proof (video or image): https://imgur.com/a/TubO1Hl

**Comment by FiuryMan** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/902

Already reported here
