### ISSUE TITLE
[Spell][NPC] Warbringer Mox'na id:90164

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#955]
Current behavior: Stands still. One of his abilities has excessive visual range.

How it should work: He should be patrolling with his felhounds, and the visual on the spell in the image should be smaller.

https://www.wowhead.com/npc=90164/warbringer-moxna

Proof (video or image):

![image](https://user-images.githubusercontent.com/29517963/166101745-b1816f1a-8a68-487e-9a0c-fe9eee11f817.png)

**Comment by Ragelezz** [comment]
fixed pathing and the spell removed from him, saw multiple videos where he is not using it.
