### ISSUE TITLE
[World Quest ] Azsuna 42014

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#964]
"A Tainted Vintage" ID 42014

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/969939332205011044/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/969939488572837948/unknown.png

**Comment by Ragelezz** [comment]
already in quest log
