### ISSUE TITLE
[Zone][Object] Dreadscar Rift

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#967]
Current behavior: Any class can enter the Warlock Order Hall

How it should work: The portal shouldn't work for any non-Warlock

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/166106270-7d9fcce8-9bf8-4051-8504-0f99b24e237e.png)

**Comment by Ragelezz** [comment]
fixed
