### ISSUE TITLE
[World Quest] Highmoutain 44892

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#970]
"Snowfeather Swarm!" ID 44892

When you go in the selected area the world quest doesn't active and you cannot do the world quest.

https://cdn.discordapp.com/attachments/929136522777727056/969957339341942815/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/969957795472490506/unknown.png

**Comment by Ragelezz** [comment]
log
