### ISSUE TITLE
[World Quest] Highmountain 40980

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#971]
"Boilback Plague" ID 40980

The NPC "Boilback Mauler" ID 102408 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/969959384572649562/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/969959205454884944/unknown.png

**Comment by Ragelezz** [comment]
fixed
