### ISSUE TITLE
[World Quest] Highmountain 41095

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#972]
"Critical Crops" ID 41095

The NPC "Diseased Grub" ID 94688 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/969961763988709467/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/969961787300659240/unknown.png

And for comparrison in the same are this is the damage from the NPC "Overgrown Larva" NPC ID 94691.

https://cdn.discordapp.com/attachments/929136522777727056/969963127334637658/unknown.png

**Comment by Ragelezz** [comment]
fixed
