### ISSUE TITLE
[Zone] Stormheim 

### ISSUE THREAD

**Issue by arft1kwerg** [Evolution-WoW/Bug-Report#977]
Current behavior: Dying in the south-eastern parts of Stormheim places you under the ground.

How it should work: Should place you above ground at the GY

Proof (video or image):
![image](https://user-images.githubusercontent.com/29517963/166110618-3ab20369-e0aa-44ed-a569-7ec45a0fb58f.png)

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/1040
