### ISSUE TITLE
[Herbalism] Highmountain Zone

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#984]
In Highmountain, the zone that has the highest spawn rate for Foxflower, has only 31 spawn spots for Foxflower and nothing else. (Picture with my gather mate for the spawn points)

https://cdn.discordapp.com/attachments/898956604467191818/970022804214923384/unknown.png

And there should be 331 spawn points:

https://cdn.discordapp.com/attachments/898956604467191818/970023805621772398/unknown.png

**Comment by Ragelezz** [comment]
There are 264 spawns of Foxflower, no issue.
