### ISSUE TITLE
[Herbalism] Zone Stormheim

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#986]
In Stormheim, the zone that has the highest spawn rate for Fjarnskaggl, has only 27 spawn spots for Fjarnskaggl. (Picture with my gather mate for the spawn points).

https://cdn.discordapp.com/attachments/898956604467191818/970026865177796618/unknown.png

And there should be 597 spawn points:

https://cdn.discordapp.com/attachments/898956604467191818/970029723612770426/unknown.png

**Comment by Ragelezz** [comment]
There are 483 spawns of Fjarnskaggl, no issue.
