### ISSUE TITLE
Bugged Quest "The Riddle of the Barrel"

### ISSUE THREAD

**Issue by Flooffers** [Evolution-WoW/Bug-Report#989]
Quest name as in the title.
as shown in the screenshot after killing the mob named "Vadis" it should drop a barrel where you loot the item to complete the chest but there is nothing to loot. The screenshot says it all
![BuggedQuest](https://user-images.githubusercontent.com/104695076/166119836-db62e895-a730-4816-9109-d06827ca356b.PNG)

**Comment by Redbaronn** [comment]
This quest was done today without any issue, try to retake the quest and delete cache. Proof that the whole class hall campaign is working in the picture.

https://cdn.discordapp.com/attachments/895446386449981471/970082177184313484/unknown.png

**Comment by Foxy19o** [comment]
Retake the quest, I was able to complete it too.
