### ISSUE TITLE
Bugged Mission Table at Monk Classhall.

### ISSUE THREAD

**Issue by Flooffers** [Evolution-WoW/Bug-Report#990]
Current behavior: I behave very well

How it should work: there should be a table where I drew "insert TABLE here" for classhall missions

Proof (video or image): a screenshot
![BuggedTable](https://user-images.githubusercontent.com/104695076/166120066-d8ca1a85-2bb7-488f-b34d-4dc821f8a308.PNG)

## DON'T FORGET TO LABEL IT ACCORDINGLY TO THE ISSUE.
ok
![BuggedTable](https://user-images.githubusercontent.com/104695076/166120057-8280cfc8-b723-4879-b27a-689c4782a6a8.PNG)

**Comment by Flooffers** [comment]
sorry I accidently posted the screenshot twice

**Comment by Redbaronn** [comment]
I just tested it, there is a mission table, try to relog or delete cache. I'll send you pictures as a proof.

https://cdn.discordapp.com/attachments/895446386449981471/970081651336020060/unknown.png
https://cdn.discordapp.com/attachments/895446386449981471/970081721808715836/unknown.png

**Comment by Ragelezz** [comment]
you need to do the class hall quests in order to mission table to appear, invalid
