### ISSUE TITLE
[NPC Wrong Scalling] Val'sharah

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#991]
The NPC "Felclaw Fiend" ID 115379 currently the damage is scaled for 7.3.5

https://cdn.discordapp.com/attachments/929136522777727056/970076973202296872/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970076782931898408/unknown.png

**Comment by Ragelezz** [comment]
fixed
