### ISSUE TITLE
[Herbalism] Val'sharah Zone

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#992]
In Val'sharah, the zone that has the highest spawn rate forDreamleaf, has only 36 spawn spots for Dreamleaf. (Picture with my gather mate for the spawn points).

https://cdn.discordapp.com/attachments/898956604467191818/970089939238805644/unknown.png

And there should be 626 spawn points:

https://cdn.discordapp.com/attachments/898956604467191818/970090048974377021/unknown.png

**Comment by Ragelezz** [comment]
There are 485 spawns of Dreamleaf, no issue. Those 626 from wowhead are estimative spawns pinned by other users.
