### ISSUE TITLE
[Herbalism] Suramar Zone

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#993]
In Suramar, the zone that has the highest spawn rate for Starlight Rose, has only 28 spawn spots for Starlight Rose.
(Picture with my gather mate for the spawn points).

https://cdn.discordapp.com/attachments/898956604467191818/970078704908795904/unknown.png

And there should be 827 spawn points:

https://cdn.discordapp.com/attachments/898956604467191818/970091230488829962/unknown.png

**Comment by Ragelezz** [comment]
There are 801 Starlight Rose spawns, no issue.
