### ISSUE TITLE
[NPC Multistack] Azsuna

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#996]
The NPC "Withered Outcast" ID 91157 is spawned multiple times on the same spot I cannot even count how many mobs are there.

https://cdn.discordapp.com/attachments/929136522777727056/970105139178373120/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970105832811397130/unknown.png

Coordinates: https://cdn.discordapp.com/attachments/929136522777727056/970105953993261056/unknown.png

**Comment by Ragelezz** [comment]
fixed
