### ISSUE TITLE
[World Quest] Azsuna ID 43606

### ISSUE THREAD

**Issue by Redbaronn** [Evolution-WoW/Bug-Report#998]
The quest "WANTED: Arcavellus" ID 43606 triggers on a wrong spot in Azsuna (the difference is big, its on the opposite side of the map where should the initial quest and trigger be).

https://cdn.discordapp.com/attachments/929136522777727056/970288795935182898/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970288840185090109/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970288368564969472/unknown.png
https://cdn.discordapp.com/attachments/929136522777727056/970288291662413924/unknown.png

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/1003
