### ISSUE TITLE
[NPC wrong language] ID:91651 & ID:91109

### ISSUE THREAD

**Issue by OitzahBarsana** [Evolution-WoW/Bug-Report#999]
Inside the quest Cenarius, Keeper of the Grove (ID:40122) the NPC (ID:91651) Nyandra Springbloom's dialogue is in cyrillic. Malfurion Stormrage (ID:91109) also says one line in cyrillic.
Proof (video or image):

![image](https://user-images.githubusercontent.com/104162698/166144734-0a0daa65-bee2-47dc-ac1d-c6922698d64c.png)

**Comment by Ragelezz** [comment]
fixed
